### ISSUE TITLE
iSpindel POST to BrewPiLess fails

### ISSUE THREAD

**Issue by j0hnsmith** [universam1/iSpindel#102]
So I've made some videos to demonstrate (click the images to download mp4 videos)

### Shells
top: curl
middle: iSpindel (various versions)
bottom: BrewPiLess (f7b3bf1)

### iSpindel 5.5.0
The first shows iSpindel 5.5.0, the http body is appearing before the headers but maybe that's just the serial output. Note that BPL is showing `BodyStart: ... B` but the request never seems to finish. When I make a request via curl it works as expected

[![iSpindel 5.5.0](https://www.dropbox.com/s/rg6jfvzoew76l84/s85oqbgv.png?raw=1)](https://dl.dropboxusercontent.com/s/vt0w66knwxrrurc/ispindel%205.5.0.mp4?dl=0)

### iSpindel 5.1.2
This shows the http body after the headers, BPL is showing `BodyStart: ... B` but again the request never seems to finish. With curl it works as expected but after a few requests BPL seems to freeze, the second curl request doesn't connect. I think the freeze is issue [referenced in the BPL readme that's now been resolved](https://github.com/vitotai/BrewPiLess#ispindel-support).

[![iSpindel 5.1.2](https://www.dropbox.com/s/ivyy0ciorzmky61/m7wrbp0j.png?raw=1)](https://dl.dropboxusercontent.com/s/257qfdos8cudzqf/ispindel.5.1.2.mp4?dl=0)

### iSpindel 5.1.2 ([BPL extra](https://github.com/vitotai/BrewPiLess/blob/master/extra/iSpindel-BPL.5.12.bin))
This is the only version that I've been able to get working, I'm not sure what is different in this version. Note that the http POST request takes around 13 seconds to complete, that is a _very_ long request. The curl request seems to take a fraction of a second. 

@vitotai What's different about [this](https://github.com/vitotai/BrewPiLess/blob/master/extra/iSpindel-BPL.5.12.bin) version of iSpindel?

[![iSpindel 5.1.2 BPL](https://www.dropbox.com/s/a3b6nb54as13w5f/c00db5f5.png?raw=1)](https://dl.dropboxusercontent.com/s/785rg6cc1c9b7dw/ispindel.5.1.2.BPL.mp4?dl=0)

## Bug
It seems odd that the POST request should take more than say 250ms, I'm guessing the fact that it takes ~13 seconds is part of the problem, where it's not working I suspect something is timing out before the request is complete. However the big question is why does it take so long in the first place?

@vitotai Do you have any idea why this might be happening?

**Comment by universam1** [comment]
Thanks for the feedback!
Here is a bugfixed version, using a library now to perform the post. Please also monitor the execution time in this regard and let me know how it works.
[firmware.zip](https://github.com/universam1/iSpindel/files/1366844/firmware.zip)

**Comment by universam1** [comment]
duplication of #103

**Comment by j0hnsmith** [comment]
Great news, my iSpindel & BPL are otherwise engaged (in a brew) so it'll be a while before I can test and report back.
