### ISSUE TITLE
stainless steel fermenter - faradic cage

### ISSUE THREAD

**Issue by Philusha1983** [universam1/iSpindel#105]
I want to use the iSpindel inside my SSBREW-TECH bucket (stainless steel)
Had anyone tried to use iSpindel inside metal fermenter?
Any issues that might appear?  
I wonder if Faraday cage effect might be in this case.

**Comment by universam1** [comment]
Sure this is working by a lot of users. Though there are a few things possible or required to achieve sufficient wifi coverage. Following attempts can help:

1. break up the faradic cage. This is possible by electrically disconnecting the lid from the pot. This effectively opens the pot. Can be done by putting a silicon sealant between.
2. insert a passive antenna. Use a shielded cable that is stripped off exactly with 3.2mm from both ends ( that is Lambda/4) where one side ends in the pot. This will passively transmit from inside out and vice versa. There is a good example here: http://hobbybrauer.de/forum/viewtopic.php?p=208782#p208782
3. use a wifi range extender to boost the signal level. Put a wifi extender just next to the pot and the signal is increased enough.
