### ISSUE TITLE
Container options

### ISSUE THREAD

**Issue by vytux-com** [universam1/iSpindel#106]
I am struggling to find a decent source of PET Preforms as required for this project. I did manage to get hold of a PET bottle with the same diameter top and only slightly longer than the preform. However it is a bit wider at the bottom and has the standard bottle flared bottom.
![image](https://user-images.githubusercontent.com/5370583/31335502-9ec017e6-ad3e-11e7-8c35-75224e959d45.png)
Would it be possible to use this instead and are there any requirements for getting this to tilt correctly?

**Comment by universam1** [comment]
This is hard to say if it will work or not, you are basically on your own to try. 
However, you should be able to buy a PET preform which is hard to find but usually available through geo caching shops.

**Comment by vytux-com** [comment]
Unfortunately the only ones I could find were in Europe and shipping them half way around the globe makes them way too expensive.

If the container was 25mm or so too long would you extend the drawer by that amount or would you pack something in the bottom of the bottle?

**Comment by Philusha1983** [comment]
http://www.ebay.com/itm/132339878510?ssPageName=STRK:MESELX:IT&_trksid=p3984.m1555.l2649

**Comment by bralexc** [comment]
You don't _have_ to use the 3D printed drawer from the project. After you've selected a bottle, you can make your own drawer with any light material that is easy to sculp, like balsa wood or styrofoam. Just be sure that the components don't juggle around once you've mounted everything. You might also have to play a little with the extra weights to get the CG in place.

**Comment by filipematos95** [comment]
> http://www.ebay.com/itm/132339878510?ssPageName=STRK:MESELX:IT&_trksid=p3984.m1555.l2649

 @Philusha1983 the PET container from that link only have a diameter of 33 mm, there are no drawers for that diameter.

**Comment by Philusha1983** [comment]
This is the correct link.
I bought it and used the pet to make several ispendels

**Comment by filipematos95** [comment]
@Philusha1983 which .stl file did you use for those PET?

**Comment by Philusha1983** [comment]
https://github.com/universam1/iSpindel/blob/master/drawer/drawer-combo-short-spring2.stl

**Comment by universam1** [comment]
assume it is fine, so closing for now
