### ISSUE TITLE
V3 of the wemos just arrived

### ISSUE THREAD

**Issue by charliwest** [universam1/iSpindel#109]
Anyone able to confirm if the newest version works?

**Comment by universam1** [comment]
Have some links?

**Comment by charliwest** [comment]
http://s.aliexpress.com/fmAvuEju

**Comment by zoomx** [comment]
It seems that the only hardware modification is the jumper fo deep sleep (GPIO16 to reset pin).

**Comment by charliwest** [comment]
Ive got some one the way so can hopefully confirm in nov if it works ;)

**Comment by maramu** [comment]
Hello,
I bought the version [V2.3.0 D1 mini](https://wiki.wemos.cc/products:d1:d1_mini), I would like to know if I had to buy a new wemos (older version) or If I can use this version. Moreover, I do not know where is the diode. Please, help me!
Thank you so much,
Martín

**Comment by universam1** [comment]
not tested myself, but it looks ok to go. The diode is on the same spot as before and has a printing of `SL` on.

**Comment by charliwest** [comment]
the 2.3 just moved the ports to the other side for space saving, everything else is the same I believe.

**Comment by Mvanmierlo** [comment]
Some pictures as a reference

![image](https://user-images.githubusercontent.com/26039442/32436891-da5ca244-c2e5-11e7-80a4-11f87e880b7a.png)

![image](https://user-images.githubusercontent.com/26039442/32436990-2a2ad62e-c2e6-11e7-8831-9eccc0b54de4.png)

**Comment by maramu** [comment]
Thank you very much!.

**Comment by universam1** [comment]
assume works all good, so closing for now
