### ISSUE TITLE
Calibration help

### ISSUE THREAD

**Issue by charliwest** [universam1/iSpindel#115]
Must have got something super wrong with my calibration. I followed the easy steps, got a nice curve on the tool, plugged in my calculation ...and the out put is 
```iSpindel000,3765177,74.9494,21.125,3.816475,25.95141```
where
```spindle_name,spindle_id,angle,temperature,battery,gravity```
I'm pretty sure the gravity of my beer wasn't 25.95141 :)
It did change a bit, getting down to 23.77498 during fermentation.
Should I have removed the calculation in the webui before doing calibration?

-0.00031*tilt^2+0.557*tilt-14.054 was the calculation I ended up with...not sure if that looks crazy or ok

**Comment by universam1** [comment]
seeing your angle is 74.9494 which is completely outside of any sane area. 
You have to trim the iSpindel mandatory to about 25° angle in plain water, your one is laying almost flat. That is never going to work.

**Comment by charliwest** [comment]
Thanks @universam1 

Can you confirm if I should take the calculation out before reconfiguring it please?

**Comment by universam1** [comment]
A not correct formula does hurt as long you ignore the false gravity during your calibration time

**Comment by riisefrutti** [comment]
Just as a side note. I have testet in the range aprox 15 to 25 with great success. Stable readings.

**Comment by temistokles** [comment]
@charliwest I seem to be having the same problem. I cannot get the tilt below 60° (it seems to only show interval between 60-90°). Any idea what might be the problem?

**Comment by thegreatgunbantoad** [comment]
@temistokles assuming you have done the offset cal. routine on a flat horizontal surface with the gyro face up and it's still an issue, then you probably have a duff gyro board.  Seen similar issues myself.
