### ISSUE TITLE
Send interval

### ISSUE THREAD

**Issue by cwilling** [universam1/iSpindel#116]
Currently there is no way for a server to know when the next data transmission from an iSpindel will occur. Some services (like Ubidots which just display graphs of whatever data have been received) don't care - they just keep waiting.

Other services may actually use the received data for something important e.g. making beer. In this case, the server might be switching an external device like a fridge on or off according to some algorithm which bases its decisions on the data received from an iSpindel. A question arises of what the algorithm should do when (for whatever reason) transmissions from the iSpindel stop.

I don't want to discuss now what the algorithm should do in such a case. What I would like to discuss is how the server can detect that contact with the iSpindel has stopped. In my own software, I have a configuration setting so that the user can set a time limit such that if the server does not receive a data transmission within the configured time limit, it assumes the iSpindel has died. I generally advise this setting to be a a small amount (say 5%) over two times the sleep interval of the iSpindel itself e.g.  sleep interval 300s => time limit 630s. The rationale is that we may forgive the loss of 1 data transmission but if we lose two consecutive transmissions, we should start to worry that something is wrong.

The manual configuration method works well enough but a problem arises when a user has configured the iSpindel with a quite short sleep interval (maybe for calibration or testing etc.) and later reconfigures the iSpindel for a longer sleep interval, perhaps to start some real work, but forgets to set a new time limit in the server. 

Due to a manual oversight like this, the software now doesn't wait long enough for data transmissions and wrongly assumes it has to deal with a dead iSpindel. It would be better not to depend on the user always doing the right thing (remembering to update the software time limit to match the iSpindel). It would be far preferable if the timeout could be set programmatically. This would require that the software can know what the iSpindel sleep interval has been configured to be. The software could know this if the iSpindel would include the sleep interval in its regular data transmissions.

I have modified the iSpindel firmware locally to include the sleep interval and it works quite well. I will submit a PR with the changes shortly. In the meantime, are there any comments about the situation? Any other solutions for the same problem?

**Comment by universam1** [comment]
In general, this is a pretty specific issue, I am not aware of other software that is considering an update health. 
Nevertheless, I think your reasoning is good and I like the simplicity to solve this challenge, we should merge it.

Now there are a few doubts about some protocols that are proprietary and will likely break, I suggest we leave them out for now. If the stakeholder decide to support we can add them individually anytime.
