### ISSUE TITLE
Angle Issue...

### ISSUE THREAD

**Issue by dxcoco2** [universam1/iSpindel#120]
I've bought the kit on-line...
i've solder all the board and connection...after flash the firmware i've exec the calibration and i follow all step with water and sugar but....the angle is the same for every solution density!
0°P -> 76,8
2,5°P -> 76,7
5°P -> 76,8

why?

if i force the Ispindle in vertical position, the angle value is 1,5/2°...the gyroscope is ok!
Thanks

**Comment by benbroadley88** [comment]
It looks like your device isn't heavy enough. In plain water (0°p / 1.000 SG) the device should float around 25°. Try adding a bit more weight to it and you should see a greater change in angle as the gravity increases/decreases

**Comment by benbroadley88** [comment]
It looks like your device isn't heavy enough. In plain water (0°p / 1.000 SG) the device should float around 25°. Try adding a bit more weight to it and you should see a greater change in angle as the gravity increases/decreases

**Comment by dxcoco2** [comment]
ok i try....thanks!

**Comment by dxcoco2** [comment]
I've add a weight and now is ok! This week i perform  a calibration with a sugar solution!
Thanks for your help!
