### ISSUE TITLE
Question about #define ADCDIVISOR 191.8

### ISSUE THREAD

**Issue by lupin982** [universam1/iSpindel#125]
Hi, a simple question about ADCDIVISOR.
Why the  ADCDIVISOR = 191.8?
Since you are using R = 230K between A0 and power voltage, i assume the maximum voltage is 5.5V = 1V*(100k+220k+230k)/100K, this means that the ADCDIVISOR should be 1024/5.5=186.18.

thanks

**Comment by universam1** [comment]
This is theoretically correct, realistically this value has been an average of a number measured setups to be a good starting point. 

Check the FAQ to see that one would anyway want to fine tune his factor which is individual eventually.
