### ISSUE TITLE
 problem with the battery voltage information, with zero value always

### ISSUE THREAD

**Issue by rlfaquino** [universam1/iSpindel#129]
Hello, i have a problem with battery volts variable, it always shows a zero value, the ispindel is not reading the battery voltage, 

even in the configuration mode information page (192.168.4.1), the value of the battery voltage information variable always remains zero

the other values of the other variables are ok

can you help me?

**Comment by rlfaquino** [comment]
![screenshot from 2017-12-30 02-59-36](https://user-images.githubusercontent.com/34952829/34451466-a0fcae3e-ed0d-11e7-88ea-fed6a5c5c025.png)

**Comment by universam1** [comment]
You need to check the pin `A0` that it has around 3V. I strongly assume you got a short cut to GND there.
