### ISSUE TITLE
How do I reset the "calibrate" if used i maintenance menu?

### ISSUE THREAD

**Issue by tedelm** [universam1/iSpindel#133]
How do I reset the "calibrate" if used i maintenance menu?

I have noticed that when this funktion is used, the tilt value starts to get higher at ~60° tilt. From 80 to 60 its fine but then it starts to increase again.

**Comment by universam1** [comment]
You can calibrate any time again if not successfully performed. Lay it flat and don't move during process as shown by the pictogram.
Apparently I don't understand what you mean with tilt goes higher when it gets higher...

**Comment by tedelm** [comment]
Re-flashing the firmware doesnt seem to reset the calibration

**Comment by tedelm** [comment]
I read thru the code. Could you please insert a button to reset the "my_****" variables used for mpu calibration?

**Comment by universam1** [comment]
It’s saved along with the other settings in the config file. You have a hardware issue or you are somewhat performing the calibration in a different way. 
Easiest to reset is to flash a firmware that does a spiffs formatting, I think there is even an Arduino example of that ready available

**Comment by tedelm** [comment]
Not tested yet, but here is a .bin file that will format the SPIFFS/CFGFILE.... https://github.com/tedelm/MRTEEL/tree/master/BIN/FormatSPIFFS

**Comment by universam1** [comment]
@tedelm check out new FW v. 5.7.0 where I introduced a `Factory Reset` feature if that fits your needs.

**Comment by tedelm** [comment]
Nice work, thanks!
