### ISSUE TITLE
Suggestion: Let iSpindel transmit signal strength

### ISSUE THREAD

**Issue by PjotrekSE** [universam1/iSpindel#137]
For us with a stainless steel fermentor, it would be nice if the iSpindel could also transmit signal strength. At least as an option. That would make it easier to test out optimal or sufficient positioning of router or repeater.

**Comment by universam1** [comment]
sounds like a good idea!

**Comment by universam1** [comment]
@PjotrekSE Try the new firmware version 5.8.0 that transmits the RSSI in dBm. Let me know how it goes.

**Comment by PjotrekSE** [comment]
Nice. I will try it out as soon as the current battery test is finished.

Den 9 feb. 2018 20:13 skrev "universam1" <notifications@github.com>:

**Comment by PjotrekSE** [comment]
Tested. Works like a charm. Was able to find the best position for the repeater, astonishingly not directly above the fermenter, but about 10 cm above and 15cm to the side. Here are the results:
Free air, 15cm distance, -35 dB
Free air, 60cm distance, -45 dB
65 liter steel fermenter with 55 liter water, fitted with 15mm silicon plug and fermentation valve:
10 cm above, 00 cm to the side: -57 - -50 dB
30 cm above, 00 cm to the side: -56 - -55 dB
60 cm above, 00 cm to the side: -59 - -57 dB
60 cm above, 15 cm to the side: -73 - -68 dB
30 cm above, 15 cm to the side: -67 - -57 dB
30 cm above, 15 cm to the side: -63 - -56 dB
10 cm above, 15 cm to the side: -56 - -51 dB

**Comment by universam1** [comment]
Awesome 👏
