### ISSUE TITLE
Flash Wemos D1 mini on a MAC

### ISSUE THREAD

**Issue by abdulson** [universam1/iSpindel#14]
You mentioned a Win-tool for flashing Wemos.
I only have a Mac on my site. What will the right tool for flashing?
I tried Arduino IDE, but git a cimpilation error:

Arduino: 1.8.0 (Mac OS X), Board: "WeMos D1 R2 & mini, 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from /Users/mst/Downloads/iSpindel-master/iSpindel/iSpindel.ino:16:0:
sketch/Ubidots.h:39:76: fatal error: ArduinoJson.h: No such file or directory
 #include <ArduinoJson.h>         //https://github.com/bblanchon/ArduinoJson
                                                                            ^
compilation terminated.
exit status 1
Fehler beim Kompilieren für das Board WeMos D1 R2 & mini.

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by universam1** [comment]
You are missing the required library, see here 
https://github.com/universam1/iSpindel/blob/master/docs/compile.md

You can also flash directly described here:
https://hackaday.io/page/1223-how-to-flash-nodemcu-on-mac-os-x-yosemite
