### ISSUE TITLE
Possibility of save locally the data and upload when connection is available

### ISSUE THREAD

**Issue by Perimec** [universam1/iSpindel#140]
Dear,
thanks a lot for the current project. it is really amazing the work that you are doing here.

However I have a simple question/suggestion. Most people, like me, do the fermentation in a remote place of the house (most probably in a temperature controlled fridge or similar). In my case, I have no wifi in this place. 

I was then thinking, would be possible to save the data locally on the memory and then use a phone (acting as access point) to upload the data on the cloud? 

Thanks

**Comment by Philusha1983** [comment]
Have you thought about WiFi repeater? They not pricy and might solve your
problems

**Comment by Perimec** [comment]
I have the fermentation in the attic and there are other apartment in the middle... a repeater would not help...

**Comment by ollinator2000** [comment]
Ich had similar problems. I solved this by using a Mini Wifi AP and a Raspberry Pi . The Spindel and the Rpi are connected to this closed wifi network . everytime i m near the fermenter ( in my case this is the cellar ) i connecting to this network with my phone an check the data.

**Comment by Perimec** [comment]
uhh that could be a good idea.. but I cannot understand how it works. The Spindel is sending the data to the RPI and do you have a code running there that saves the data?

**Comment by universam1** [comment]
That is a better approach from @ollinator2000 to solve this problem. There is a principle problem with that the iSpindel has no internal clock available other than sourced from internet which is a catch 22 situation. Also it is questionable that you would be in range right in time when it wakes up. Also the battery lifetime makes it impossible to host an Accesspoint itself, so basically this is not possible.

**Comment by ollinator2000** [comment]
Yes , I’m running the tcp Server programmed by Tozzi on my RPI ! 😉 
https://github.com/DottoreTozzi/iSpindel-TCP-Server

**Comment by Perimec** [comment]
Thanks for all you comments :)
