### ISSUE TITLE
Circuit diagram

### ISSUE THREAD

**Issue by Perimec** [universam1/iSpindel#145]
Dear,
thanks again for the wonderful tool that you have been developing here. 

I'm building my first ispidel and I have a question regarding the circuit diagram (https://github.com/universam1/iSpindel/blob/master/docs/circuit_diagram_en.md). The orange cable connecting the the +in lipo to the +5v of the wemos is optional if understood correctly. What is it for? and then if I will not use it, shall I still remove the input diode on the wemos? and what does it mean in the description : Remove the input diode (short circuit via Lipomodul!)??? is that optional too?

thanks in advance

**Comment by universam1** [comment]
The orange is optional, you can also just use the USB connector of the charging module to charge.

The diode is to be removed to prevent uncontrolled charging of the LiPo through the USB connector of the Wemos, so if you love your home you should remove it in order to prevent battery explosion. :)
