### ISSUE TITLE
Additional upload possibility added

### ISSUE THREAD

**Issue by gmorfeus** [universam1/iSpindel#148]
Hi,

This is not really an issue but more an added functionality to let others know what I did, and if someone needs similar functionality, well, let me know:)
I am working on a "temperature chamber" that will be used for controlling temperature in the fermentation process. The "brain" will be an Wifi enabled Arduino. As I would like to have information from iSpindel on Ubidots and also have Arduino to have as much as possible precise temperature, I have added a possibility to configure two separated uploads. So connecting Arduino and iSpindel on the same Wifi, I'll configure iSpindel to send data to Arduino and Ubidots at the same time. I made all this upgrades on version 5.8.2 of iSpindel firmware.

**Comment by universam1** [comment]
There are two featured project using a Raspberry Pi out there and one using an Esp8266 called BrewPiLess that do these automation. 
Calling several backends from iSpindel is a bad idea regarding life time.
