### ISSUE TITLE
Please help me -Ispindel config - no com port

### ISSUE THREAD

**Issue by SimonHanson** [universam1/iSpindel#149]
Windows 10
When i plug in my ispendel i can not getting a com port showing in device manager
Therefore cant flash it

**Comment by JensW2000** [comment]
Do you probably forgot to install the CH350G Device driver?
https://wiki.wemos.cc/downloads

**Comment by SimonHanson** [comment]
Installed still not working

________________________________

**Comment by JensW2000** [comment]
Please connect a USB cable to the charging module (TP4056).
Wich lights does lit after a single reset? What lights does lit if you turn off the power switch?

**Comment by SimonHanson** [comment]
Switch position one
PLug in USB Blue light on, tiny orange flash on the other led
hit reset  nothing

Switch position 2
Plug in uds blue and orange lights on 
hit reset blue light on the other board

**Comment by SimonHanson** [comment]
Please can anyone help me with this problem

**Comment by universam1** [comment]
no progress on this one, closing

**Comment by SimonHanson** [comment]
I still need to get an answer

________________________________
