### ISSUE TITLE
Remove SerialOut function

### ISSUE THREAD

**Issue by FernandoGarcia** [universam1/iSpindel#160]
Hi!

I was thinking that is possible save a lot of RAM when debug is disable replacing the **SerialOut** function by standard **Serial.print** function. 

Using **#ifdef** conditions won't add debug code to be compiled.

I'm talking in something like this:

```
#ifdef DEBUG
   Serial.print(F("applying offsets"));
#endif
```

Instead:

`SerialOut(F("applying offsets"));`

The code will be a little ugly but will save RAM and FLASH.

If do you agree I'll make the changes.

Other suggestion is welcome.

Best regards.

**Comment by universam1** [comment]
You are assuming that the serial output is for debugging, at the beginning of the project I assumed it as well.

However, it is the console output, the only source for the users to determine the behaviour or errors happening. Hence, removing the console output is like shooting in the leg.
