### ISSUE TITLE
connection issue? no values shown

### ISSUE THREAD

**Issue by stefanK74** [universam1/iSpindel#162]
I have a CBP3.0 installation, iSpindel plugin activated and the iSpindel configured properly which works well with Ubidots, but when configured to connect to CBP it doesn´t seem to. I am able to create iSpindle sensors in CBP´s configuration but no values are shown at all.
I checked the trace via USB - no errors. iSpindel also connected to the wifi properly. Looking at /craftbeerpi3/logs/ there is no S_1.templog file created? Any help would be much appreciated! Thank you!

**Comment by universam1** [comment]
If you see no error in the console the apparently there is a problem with CBP, right?
