### ISSUE TITLE
The gravity increases at initial fermentation

### ISSUE THREAD

**Issue by einaruk** [universam1/iSpindel#168]
Yesterday night, I started an experiment of tracking gravity and temperature with iSpindel implementation. 
The thing is, as you can see from the below chart, the gravity has been increased to 1.070 from 1.055 in 4 hours, and it dropped back to OG value again in 10 hours.

Now the gravity inclined to drop as expected.

I am not able to justify why there had been an increase in gravity at the early stages of fermentation. I do not expect it to be because of wrong interpretation of the sensor signals. 

More details:
- The fermenting liquid is mixture of sugar and water. The yeast is regular baking yeast
- The fermantation container is an open bucket
- There is some Krausen formed but it is not in contact with the iSpindel
- As can be seen the temperature is quite constant
- There is no mechanical impact/strike to fermentation bucket and it is sitting on a flat place.
- Bucket is wide enough and water level is high enough so that the iSpindle is not affected by the walls or bottom of the bucket
-  In my previous experiments where I compared the iSpindel results with hydrometer readings, the reading sensitivity was good (10 samples read with different gravity solutions).

My initial theory is that, since the yeast is top-fermenting yeast, it first changes the density of the surface ( but even in this case, the high gravity liquid should go to bottom since it is heavier).

Any ideas about the case? May it be a chemical reaction that is causing the reading to be high? 
![gravity chart](https://user-images.githubusercontent.com/7220667/37402553-121819c2-279d-11e8-9f59-f9f489fd39ef.PNG)

**Comment by universam1** [comment]
This is very common because of the CO2 and the lift resulting from.

That's why I highly suggest calibrating this method https://github.com/universam1/iSpindel/blob/master/docs/Calibration_en.md#improved-method-using-fast-fermenting-ii that incorporates this error and thus takes that into account
