### ISSUE TITLE
polynominal gets cut after 38 signs

### ISSUE THREAD

**Issue by Redsak** [universam1/iSpindel#172]
the polynomynal gets cut after 38 signs, or, if () is used gets gibberish after that.

**Comment by universam1** [comment]
Please provide an example

**Comment by Redsak** [comment]
As shown in the pics it gives me somethin like in the second pic if i 
put in more than 38 signs or use ()

Am So, 8. Apr, 2018 um 7:13 P. M. schrieb Samuel Lang 
<notifications@github.com>:

**Comment by universam1** [comment]
@Redsak Please try this version and feedback if it solves your issue. Think I found a problem where encoded character actually take up more space than assumed

[firmware.zip](https://github.com/universam1/iSpindel/files/1929150/firmware.zip)

**Comment by Redsak** [comment]
Ok, will do tomorrow

Samuel Lang <notifications@github.com> schrieb am Do., 19. Apr. 2018, 19:32:

**Comment by badcrc** [comment]
Hi, I tried it (had the same issue with strange characters in the polynomial) and seems to work.
