### ISSUE TITLE
HTTPS endpoints gives response http-code 301 (redirect)

### ISSUE THREAD

**Issue by tgangso** [universam1/iSpindel#173]
Is there any plan for supporting https endpoints?

Thank you

**Comment by universam1** [comment]
Can you describe your setup and issue more clearly?

**Comment by tgangso** [comment]
Basically i want to integrate the ispindel into my brewing app www.brewfather.net, but my backend only supports https, i have tested against my endpoint https http://app.brewfather.net/testEndpoint using protocol http, server app.brewfather.net and serverurl /testEndpoint. It gives http response of code 301.

Feel free to test against my endpoint.

**Comment by tgangso** [comment]
I have now set up a reverse proxy to make it work w/o this. But a direct fix would be better.
