### ISSUE TITLE
Battery charged but not powering iSpindel

### ISSUE THREAD

**Issue by nevryn** [universam1/iSpindel#175]
Hi,

I have my iSpindel working but only off USB power. AFAICT the battery charges and is fully charged but once the USB lead is unplugged the iSpindel no longer appears to be powered. I've left it running for several hours and no data is sent. 
Is there a way to check to see if the device was running when on battery power - logs etc? Or a way with a voltmeter to see if power if getting to the right pins on the various boards? 
If power isn't getting to the right places then it's probably down to my soldering but I've already been around all the joints and re-soldered them once. Is there somewhere specific I should focus on?

Thanks,

Mike

**Comment by universam1** [comment]
Look in the FAQ how to open the log console, that way you can monitor everything. Also a Multimeter on 5V pin helps to shed some light
