### ISSUE TITLE
Temp probe not working

### ISSUE THREAD

**Issue by GasGasMan74** [universam1/iSpindel#180]
Good evening,

I try desperately to make the temp probe working but it is always showing me -127°C and I don't know why, I soldered correctly all the components but I did not remove the diodes.

Could you help me ?

Sincerely

Romain

**Comment by 3DMech** [comment]
Hello Romain,
hopefully the Issue was fixed by replacing the temp-Probe.
Best,
Tjorben
(3D-Mechatronics)

**Comment by mr-bridger** [comment]
i saw this on an ispindel i made recently, constantly showed -127. after resetting a few times, and trying to clear settings (for some reason it still wouldn't remove the SSID / password etc) it finally showed the correct temperature. so the ds18b20 obviously isnt faulty. maybe a bug?

**Comment by universam1** [comment]
This is clearly a hardware issue. This value expresses there is no communication to the temp sensor.
