### ISSUE TITLE
Temperature is not sending to TCP Server

### ISSUE THREAD

**Issue by svenp** [universam1/iSpindel#184]
Hi,
the TCP Server shows Temperature in Charts but it is the gravity value not Temperature . In Spindle Info the Temperature is shown correct
Affter a look in Database i see gravity values in Database temperature field.

So latest iSpindle Firmware send wrong value to TCP server, or Dataformat between TCP Server and Spindel does not match.
Best Regards Sven

**Comment by svenp** [comment]
Hi,
look like a timing Problem with DS18B20
When i look at Info there is correct Temperature, maby DS18B20 has more delay time when creating website.
I changed code here delay time from 100 to 200 
`  if (block)
      {
        CONSOLELN(F("OW Retry"));
        initDS18B20();
        delay(OWinterval + 200);  //100 -> 200
        t = getTemperature(false);
      }`
now i get correct Temperature in TCP Server. 
Best Regards
Sven

**Comment by svenp** [comment]
Ok i changed back from 200 to 100 and make some changes in Globals.h

`#define OWinterval (950 / (1 << (12 - RESOLUTION))) //800ms is to short for some Sensor changed to 950ms`

**Comment by universam1** [comment]
thats apparently an issue with the server, please open a case there
