### ISSUE TITLE
Incorrect temperature readings / off set on multiple spindels

### ISSUE THREAD

**Issue by Gkire** [universam1/iSpindel#199]
2 ispindels I built have the same issue. The temperature is reported as 35.5 (every 900 seconds since last sunday) while its really 24 degrees and on the second one the temperature is a constant 26 degrees celsius every 1800 seconds (this night) which is also too hot. Outside the petcontainer the temperature readings are correct. Could it be that the charger component which is located nearest to the tempsensor radiates some heat on start up which causes false but constant readings?
![20180822_081549](https://user-images.githubusercontent.com/42513396/44446329-b86bd000-a5e4-11e8-822c-0b4151fdff37.jpg)

![screenshot_20180822-081251](https://user-images.githubusercontent.com/42513396/44446239-72167100-a5e4-11e8-8cd0-3358b960fd1d.png)
![screenshot_20180822-081419](https://user-images.githubusercontent.com/42513396/44446262-89555e80-a5e4-11e8-9ace-1effc43e4dd1.png)

**Comment by universam1** [comment]
I cannot replicate this issue but I suggest you to try new firmware 6.0.0 as here the temp flow is changed significantly

/
