### ISSUE TITLE
Schlitten

### ISSUE THREAD

**Issue by BernhardSchlegel** [universam1/iSpindel#2]
Servus,

mit welchem CAD wurde der Schlitten erstellt (Inventor, Catia,...?). Wäre es möglich, die CAD Datei - und nicht nur die STL Datei - zu veröffentlichen. Ich würde den Schlitten gerne um einen Clips für die Batterie erweitern. Dann braucht man keinen Kabelbinder (der immer anders sitzt) und die Messungen sind vergleichbarer. 

Selbstverständlich würde ich meine Revision zur Verfügung stellen!

Viele Grüße,
Bernhard

PS: Gibt's nen Zeitplan, wann der Code online kommt?

**Comment by universam1** [comment]
Hi,
Ja der Code wird veröffentlicht wenn die Testphase beendet ist und das finale Setup steht.  Damit soll eine definierter Stand getestet werden ohne Fremdvarianten die eine stabile Implemetierung schwierig gestalten.
