### ISSUE TITLE
230K Ohm resistor is not a common value?

### ISSUE THREAD

**Issue by Calimerorulez** [universam1/iSpindel#21]
Hi,

I'm trying to find a suitable resistor for the 230K one, but it isn't a common value. Can I use another value like 229K or 232K ?

**Comment by universam1** [comment]
for sure, I introduced a configuration option in the UI to adjust your changed conversion factor. And it is simple like `measured volt/displayed volt * current factor = your new factor`

**Comment by Calimerorulez** [comment]
Thank you for your quick reply! :-)

**Comment by tedelm** [comment]
So, with a mesured volt of 4.2
Displayed volt of 4.1
220kOhm resistor

(4.2/4.1)*220000=?

Or am I missing something?

**Comment by tedelm** [comment]
Or is it
(measured volt/displayed volt) * current conversion factor = new conversion factor

default conversion factor is 200

**Comment by universam1** [comment]
This is covered in the docs FAQ
