### ISSUE TITLE
battery conversion factor

### ISSUE THREAD

**Issue by MattCordell** [universam1/iSpindel#219]
I see this on the configuration screen, but can't find any details on it.
When should I change the value? How?

**Comment by FernandoGarcia** [comment]
https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md

**Comment by MattCordell** [comment]
Thanks, I saw that page. But it doesn't explain what the battery conversion is/does.
Perhaps if I don't know what it means, I just leave as default? (Though I'd like to know)

**Comment by vytux-com** [comment]
It corrects the voltage reading/display.

**Comment by FernandoGarcia** [comment]
The voltage displayed can be different according to real resistor value. So this factor is used to make the voltage displayed equivalent to voltage measured with a multimeter.

**Comment by universam1** [comment]
Thanks guys for commenting

**Comment by MattCordell** [comment]
Thanks. Is it something necessary to do? Are there consequences of not adjusting the value?
And from where should I measure the voltage? 
(Apologies in advance for commenting on a closed item)

**Comment by universam1** [comment]
Measure the battery and do that little math according to FAQ. It’s not that hard!
