### ISSUE TITLE
Feature Request: Add Brewfather as Service Type

### ISSUE THREAD

**Issue by tgangso** [universam1/iSpindel#226]
For easier configuration it would be nice if you could add Brewfather as a service type.

Currently the user select HTTP and input these values:

Server Address:
"log.brewfather.net"

Server URL:
"/ispindel?id=JgOXLRAVuBZa3b"

Where JgOXLRAVuBZa3b is a unique ID per user.

Thank you!

**Comment by universam1** [comment]
Contact me regarding licensing! @tgangso

**Comment by tgangso** [comment]
What do you mean by that?

**Comment by universam1** [comment]
Open source activities I support for free as you see, but commercial unsers require licenses. Rights reserved.

**Comment by tgangso** [comment]
Ok, how about a pull request then?
