### ISSUE TITLE
Tilt in normal water

### ISSUE THREAD

**Issue by niddu85** [universam1/iSpindel#227]
Hi everyone, I'm trying to calibrate my spindle, but I think there is something bad in the tilting of the device. My device in normal water is almost flat, parallel to the water surface (almost 90° measured by device). Is that normal? What's your tilt angle in normal water?

**Comment by mr-bridger** [comment]
Have you got a picture of it in water? Should be at 25° so something obviously wrong

**Comment by MattCordell** [comment]
It sounds like the centre of gravity of your device was too high. Lowering it deeper into tube (if possible) or adding weight at bottom of the tube (as you did). Will lower the centre of gravity (and tilt).
