### ISSUE TITLE
Zero point calbration does not work in 6.x

### ISSUE THREAD

**Issue by Misenkooo** [universam1/iSpindel#233]
Hi, I've noticed after calibration it is working properly only until I restart the device. After that the offset is not applied properly even though I can see it stored in the config file and also debug message "Applying offset" is displayed.

Please have a look. It works fine in 5.x.

**Comment by superbee383** [comment]
Hello,
Has anyone have an answer to this issue. Every time I power the iSpindle on, I have to do a calibration. If I do not do the calibration, the tilt will read between 45° and 59°. When I do the calibration the reading is between 0° and 89°.

**Comment by Misenkooo** [comment]
I've just loaded 5.x firmware. For me it works great and I don't see a point why to use 6.x. Battery life is even better for me.

**Comment by superbee383** [comment]
Ok, I'll give that a try. Hopefully, they will carry this over to the newer version.
Thanks

**Comment by superbee383** [comment]
5.x worked fine. Thanks.

**Comment by universam1** [comment]
Fixed with 6.0.5. Please make sure to `reset` under `Maintenance` menu

**Comment by stefschin** [comment]
> 
> 
> Fixed with 6.0.5. Please make sure to `reset` under `Maintenance` menu

Hi @universam1 , What do you mean about this reset? software other hardware reset?
