### ISSUE TITLE
Update calibrateSG.htm

### ISSUE THREAD

**Issue by vitotai** [universam1/iSpindel#235]
Hi Sam,

the calibrateSG.htm has some bugs and doesn't work well for Plato.
The updated version should work better.

https://github.com/vitotai/BrewPiLess/blob/master/extra/calibrationSG.htm

Forgive me for being to lazy to create pull request.
Regard,
vito

**Comment by universam1** [comment]
Thanks alot for the heads up and the fixes!
Mirrored your sources.

Thanks again!
