### ISSUE TITLE
Does not recognize 5GHz signal from either WIFI router or WIFI extender/repeater

### ISSUE THREAD

**Issue by MBjerkan** [universam1/iSpindel#238]
Using config page and the suggested available WIFI Network is only from the main WIFI Router with 2.4GHz. The 5GHz is not showing at all. The repeater network is not showing up at all in this list. Can easily read the extender WIFI list from other devices.

**Comment by avollkopf** [comment]
One resaon could be the spec of the Wemos board: [Wemos Spec](https://ucf893b7f40fa9a7d3ac1ec1823f.dl.dropboxusercontent.com/cd/0/inline2/AXFI_qw6zznj1dYNJyuM22ZXyF2POorb5rRS_xzxn2P7cM7PRZmbvhBCGfSeGN1eexixvEnppxaIYwTYUPgxiSgsvJ4BChL7nidMLuinXKGNCQ8rg9O4IP7dq5BdYS3sCUBBfX6ObihHbA4Z3EUkPBEskXYLZRjjRtO0c54p6Dk8uaQOPzQTMDmt-rWllk7rBBEhE_0QFK8VfL-VOlrtSacPP2fRs0Pk4FYGhCbyBBzUfOzxCZoY8PfNdAQP_-LN5t0HXoVmzH_lgTwWNgGVGyMiSEuS3d04K0yJIqtXyyufykmnqAwJ0_UHB-4XlOIIZ5LFVS1_OFeqTKnOPHxnYUHt9_rbdb9N-bcjzjOU490XXaFPera0NmuO4UdDG9Fryo5I-ts6HbCv0gxSipStEyVNVrvm-HIgR1X4HlwDT_X8cCFc99tdlmlU02tqqqcSQnU/file)

It supports only 2.4 Ghz

**Comment by MBjerkan** [comment]
Jepp. You are correct. Some testing today shows that a pure 2.4GHz repeater is ok for the Wemos board, but not Dual band. Especially ASUS RP-AC52. Did a test set-up with ASUS RP-N12 and it worked fine. Note sure why, but its working.

**Comment by universam1** [comment]
Esp8266 is 2.4GHz only
