### ISSUE TITLE
6.x.x not come into config mode

### ISSUE THREAD

**Issue by brunoheins** [universam1/iSpindel#243]
Hi,
I’m trying to update to 6.x version but I can’t start the config mode. The flashing led is very short when I reboot the ESP to enter configuration mode. I see the wifi point, but the power drops when I try to connect. I don't know what's wrong, but it doesn't happen with 5.x.x versions only for all 6.x version.
Any idea?

**Comment by universam1** [comment]
Where is the log file?

**Comment by brunoheins** [comment]
Log for 5.9.4 version - working config mode

PORT OPEN 115200

Communication with MCU..Got answer! Communication with MCU established.
AutoDetect firmware...

Can't autodetect firmware, because proper answer not received (may be unknown firmware). 
Please, reset module or continue.
FW 5.9.1
3.0.0-dev(c0f7b44)
Worker run!
Boot-Mode: 5
mounting FS... mounted!
	

ERROR config corrupted
...........
ERROR no Wifi credentials


going to Config Mode
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
*WM: Scan done
*WM: DUP AP: #NET-CLARO-WIFI
*WM: DUP AP: #NET-CLARO-WIFI
*WM: Adding parameter
*WM: name
*WM: Adding parameter
*WM: sleep
*WM: Adding parameter
*WM: vfact
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: tempscale
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: selAPI
*WM: Adding parameter
*WM: token
*WM: Adding parameter
*WM: server
*WM: Adding parameter
*WM: port
*WM: Adding parameter
*WM: url
*WM: Adding parameter
*WM: db
*WM: Adding parameter
*WM: username
*WM: Adding parameter
*WM: password
*WM: Adding parameter
*WM: job
*WM: Adding parameter
*WM: instance
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: POLYN
started Portal
*WM: SET AP
*WM: 
*WM: Configuring access point... 
*WM: iSpindel
*WM: Custom AP IP/GW/Subnet
*WM: AP IP address: 
*WM: 192.168.244.1
*WM: HTTP server started
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED

PORT CLOSED

**Comment by brunoheins** [comment]
log for 6.0.4 - not working config mode

PORT OPEN 115200

Communication with MCU..Got answer! Communication with MCU established.
AutoDetect firmware...

Can't autodetect firmware, because proper answer not received (may be unknown firmware). 
Please, reset module or continue.

FW 6.0.4
2.2.1(cfd48f3)
Worker run!
mounting FS... mounted!
scanning for OW device on pin: 5
No devices found!
scanning for OW device on pin: 12
No devices found!
scanning for OW device on pin: 116
No devices found!
scanning for OW device on pin: 121
No devices found!
ERROR: cannot find a OneWire Temperature Sensor!
Acc Test Connection ERROR!
Boot-Mode: External System
power-cycle or reset detected, config mode

Double Reset detected
...........
ERROR no Wifi credentials

going to Config Mode
reboot RFCAL


FW 6.0.4
2.2.1(cfd48f3)
Worker run!
mounting FS... mounted!
scanning for OW device on pin: 5
No devices found!
scanning for OW device on pin: 12
No devices found!
scanning for OW device on pin: 116
No devices found!
scanning for OW device on pin: 121
No devices found!
ERROR: cannot find a OneWire Temperature Sensor!
Acc Test Connection ERROR!
Boot-Mode: Deep-Sleep Wake

Double Reset detected
...........
ERROR no Wifi credentials

going to Config Mode
Acc Test Connection ERROR!

Exception (28):
epc1=0x4020e5c3 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3fffed00 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffeea0:  00339913 c160dd2f 3fff1ffc 401006dc  
3fffeeb0:  00000002 00000004 3fff1ffc 4020118d  
3fffeec0:  00339913 3ffef6a0 3fff1ffc 40209bc0  
3fffeed0:  3ffe8e0f 3fffef10 00000000 00000000  
3fffeee0:  3ffe8e14 3fffef08 00000000 00000000  
3fffeef0:  00000000 00000000 00000000 40209478  
3fffef00:  00339913 3ffef6a0 3ffefed8 4020eed2  
3fffef10:  00000000 00000000 3ffefca0 40209314  
3fffef20:  00339913 3ffef6a0 3fff1d7c 40209c4c  
3fffef30:  60000600 3fff1d7c 3ffef6a0 40249175  
3fffef40:  402491ba 3fffdab0 00000000 3fffdcb0  
3fffef50:  3ffef6c8 3fffdab0 00000000 00000004  
3fffef60:  40000f49 40000f49 3fffdab0 40000f49  
3fffef70:  40000e19 40001878 00000002 00000000  
3fffef80:  3fffff10 aa55aa55 00000045 4010441c  
3fffef90:  40104422 00000002 00000000 86bac8be  
3fffefa0:  4010000d 558042ff abffe145 28596d93  
3fffefb0:  40100764 3fffef4c 40100705 3ffffb78  
3fffefc0:  3fffffd0 00000000 00000000 feefeffe  
3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
3fffefe0:  feefeffe feefeffe feefeffe feefeffe  
3fffeff0:  feefeffe feefeffe feefeffe feefeffe  
3ffff000:  feefeffe feefeffe feefeffe feefeffe  
3ffff010:  feefeffe feefeffe feefeffe feefeffe  
3ffff020:  feefeffe feefeffe feefeffe feefeffe  
3ffff030:  feefeffe feefeffe feefeffe feefeffe  
3ffff040:  feefeffe feefeffe feefeffe feefeffe  
3ffff050:  feefeffe feefeffe feefeffe feefeffe  
3ffff060:  feefeffe feefeffe feefeffe feefeffe  
3ffff070:  feefeffe feefeffe feefeffe feefeffe  
3ffff080:  feefeffe feefeffe feefeffe feefeffe  
3ffff090:  feefeffe feefeffe feefeffe feefeffe  
3ffff0a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff100:  feefeffe feefeffe feefeffe feefeffe  
3ffff110:  feefeffe feefeffe feefeffe feefeffe  
3ffff120:  feefeffe feefeffe feefeffe feefeffe  
3ffff130:  feefeffe feefeffe feefeffe feefeffe  
3ffff140:  feefeffe feefeffe feefeffe feefeffe  
3ffff150:  feefeffe feefeffe feefeffe feefeffe  
3ffff160:  feefeffe feefeffe feefeffe feefeffe  
3ffff170:  feefeffe feefeffe feefeffe feefeffe  
3ffff180:  feefeffe feefeffe feefeffe feefeffe  
3ffff190:  feefeffe feefeffe feefeffe feefeffe  
3ffff1a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff200:  feefeffe feefeffe feefeffe feefeffe  
3ffff210:  feefeffe feefeffe feefeffe feefeffe  
3ffff220:  feefeffe feefeffe feefeffe feefeffe  
3ffff230:  feefeffe feefeffe feefeffe feefeffe  
3ffff240:  feefeffe feefeffe feefeffe feefeffe  
3ffff250:  feefeffe feefeffe feefeffe feefeffe  
3ffff260:  feefeffe feefeffe feefeffe feefeffe  
3ffff270:  feefeffe feefeffe feefeffe feefeffe  
3ffff280:  feefeffe feefeffe feefeffe feefeffe  
3ffff290:  feefeffe feefeffe feefeffe feefeffe  
3ffff2a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff300:  feefeffe feefeffe feefeffe feefeffe  
3ffff310:  feefeffe feefeffe feefeffe feefeffe  
3ffff320:  feefeffe feefeffe feefeffe feefeffe  
3ffff330:  feefeffe feefeffe feefeffe feefeffe  
3ffff340:  feefeffe feefeffe feefeffe feefeffe  
3ffff350:  feefeffe feefeffe feefeffe feefeffe  
3ffff360:  feefeffe feefeffe feefeffe feefeffe  
3ffff370:  feefeffe feefeffe feefeffe feefeffe  
3ffff380:  feefeffe feefeffe feefeffe feefeffe  
3ffff390:  feefeffe feefeffe feefeffe feefeffe  
3ffff3a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff400:  feefeffe feefeffe feefeffe feefeffe  
3ffff410:  feefeffe feefeffe feefeffe feefeffe  
3ffff420:  feefeffe feefeffe feefeffe feefeffe  
3ffff430:  feefeffe feefeffe feefeffe feefeffe  
3ffff440:  feefeffe feefeffe feefeffe feefeffe  
3ffff450:  feefeffe feefeffe feefeffe feefeffe  
3ffff460:  feefeffe feefeffe feefeffe feefeffe  
3ffff470:  feefeffe feefeffe feefeffe feefeffe  
3ffff480:  feefeffe feefeffe feefeffe feefeffe  
3ffff490:  feefeffe feefeffe feefeffe feefeffe  
3ffff4a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff500:  feefeffe feefeffe feefeffe feefeffe  
3ffff510:  feefeffe feefeffe feefeffe feefeffe  
3ffff520:  feefeffe feefeffe feefeffe feefeffe  
3ffff530:  feefeffe feefeffe feefeffe feefeffe  
3ffff540:  feefeffe feefeffe feefeffe feefeffe  
3ffff550:  feefeffe feefeffe feefeffe feefeffe  
3ffff560:  feefeffe feefeffe feefeffe feefeffe  
3ffff570:  feefeffe feefeffe feefeffe feefeffe  
3ffff580:  feefeffe feefeffe feefeffe feefeffe  
3ffff590:  feefeffe feefeffe feefeffe feefeffe  
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff600:  feefeffe feefeffe feefeffe feefeffe  
3ffff610:  feefeffe feefeffe feefeffe feefeffe  
3ffff620:  feefeffe feefeffe feefeffe feefeffe  
3ffff630:  feefeffe feefeffe feefeffe feefeffe  
3ffff640:  feefeffe feefeffe feefeffe feefeffe  
3ffff650:  feefeffe feefeffe feefeffe feefeffe  
3ffff660:  feefeffe feefeffe feefeffe feefeffe  
3ffff670:  feefeffe feefeffe feefeffe feefeffe  
3ffff680:  feefeffe feefeffe feefeffe feefeffe  
3ffff690:  feefeffe feefeffe feefeffe feefeffe  
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff700:  feefeffe feefeffe feefeffe feefeffe  
3ffff710:  feefeffe feefeffe feefeffe feefeffe  
3ffff720:  feefeffe feefeffe feefeffe feefeffe  
3ffff730:  feefeffe feefeffe feefeffe feefeffe  
3ffff740:  feefeffe feefeffe feefeffe feefeffe  
3ffff750:  feefeffe feefeffe feefeffe feefeffe  
3ffff760:  feefeffe feefeffe feefeffe feefeffe  
3ffff770:  feefeffe feefeffe feefeffe feefeffe  
3ffff780:  feefeffe feefeffe feefeffe feefeffe  
3ffff790:  feefeffe feefeffe feefeffe feefeffe  
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff800:  feefeffe feefeffe feefeffe feefeffe  
3ffff810:  feefeffe feefeffe feefeffe feefeffe  
3ffff820:  feefeffe feefeffe feefeffe feefeffe  
3ffff830:  feefeffe feefeffe feefeffe feefeffe  
3ffff840:  feefeffe feefeffe feefeffe feefeffe  
3ffff850:  feefeffe feefeffe feefeffe feefeffe  
3ffff860:  feefeffe feefeffe feefeffe feefeffe  
3ffff870:  feefeffe feefeffe feefeffe feefeffe  
3ffff880:  feefeffe feefeffe feefeffe feefeffe  
3ffff890:  feefeffe feefeffe feefeffe feefeffe  
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff900:  feefeffe feefeffe feefeffe feefeffe  
3ffff910:  feefeffe feefeffe feefeffe feefeffe  
3ffff920:  feefeffe feefeffe feefeffe feefeffe  
3ffff930:  feefeffe feefeffe feefeffe feefeffe  
3ffff940:  feefeffe feefeffe feefeffe feefeffe  
3ffff950:  feefeffe feefeffe feefeffe feefeffe  
3ffff960:  feefeffe feefeffe feefeffe feefeffe  
3ffff970:  feefeffe feefeffe feefeffe feefeffe  
3ffff980:  feefeffe feefeffe feefeffe feefeffe  
3ffff990:  feefeffe feefeffe feefeffe feefeffe  
3ffff9a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9f0:  feefeffe feefeffe feefeffe feefeffe  
3ffffa00:  feefeffe feefeffe feefeffe feefeffe  
3ffffa10:  feefeffe feefeffe 40243e6f 00000001  
3ffffa20:  ffffffff 00000000 3ffea531 00000008  
3ffffa30:  40243ebe 3fff1dc4 3fff1dc4 00000000  
3ffffa40:  fffffffe 00000000 4010105b 3fff1dc4  
3ffffa50:  00000000 00000000 00000020 40100f12  
3ffffa60:  3ffea3e0 40242f77 3fff1dc4 3fff0b14  
3ffffa70:  00000000 40236e0f 3ffee7bc feefeffe  
3ffffa80:  3ffe9ebf feefeffe feefeffe feefeffe  
3ffffa90:  3fff1e56 3fff086c 00000000 00000000  
3ffffaa0:  3ffe9ebf 3ffe9ebf 3fff102f 40238c1b  
3ffffab0:  3ffeeec0 40238814 402187fc 3ffeeec0  
3ffffac0:  40104d38 000bcbb7 3ffeeff0 00000000  
3ffffad0:  3ffef6a0 3ffeeff0 feefeffe feefeffe  
3ffffae0:  00000000 000b393b 4023a80f 3ffeefb8  
3ffffaf0:  3ffeeff0 402187fc 3ffeeec0 feefeffe  
3ffffb00:  3ffee840 4023a784 3ffee7bc 00000002  
3ffffb10:  40238804 402387d8 3ffee840 00000002  
3ffffb20:  402387a3 3ffee7bc 00000002 feefeffe  
3ffffb30:  40238d54 3ffee7bc 3ffee938 402187fc  
3ffffb40:  40238781 3ffee938 00000003 3ffee938  
3ffffb50:  4023ab9d 3ffffba0 0000010f 3ffee938  
3ffffb60:  3ffeff18 0000010f feefeffe feefeffe  
3ffffb70:  402187fc 4024b7f1 3ffe874c 00000000  
3ffffb80:  00000000 3ffeff18 402173b0 3fffefb0  
3ffffb90:  3ffffba0 402187fc 00000000 4021898f  
3ffffba0:  00000000 00000000 00000000 00000000  
3ffffbb0:  00000000 00000000 00000000 40100579  
3ffffbc0:  00000000 402165df feefeffe feefeffe  
3ffffbd0:  feefeffe feefeffe feefeffe 3ffffcac  
3ffffbe0:  3ffffc70 00000000 3ffeff18 40214033  
3ffffbf0:  00000010 3ffffc7c 3ffffc7c 402165df  
3ffffc00:  3ffea105 00000000 3ffffc7c 4021662b  
3ffffc10:  60000200 00000003 3ffffc7c 4021665d  
3ffffc20:  3ffea105 3ffeff18 3ffffc7c 402166aa  
3ffffc30:  3ffea105 3fff1810 000001e2 3ffefecc  
3ffffc40:  3ffea105 00000000 3ffffc70 402142b2  
3ffffc50:  3ffeff8c 3ffeff18 3ffeffac 4020b093  
3ffffc60:  feefeffe feefeffe feefeffe feefeffe  
3ffffc70:  3fff1d94 0000000f 00000000 3fff1dac  
3ffffc80:  0000000f 00000000 00000000 00000000  
3ffffc90:  3ffe97b0 00000000 00000000 00000000  
3ffffca0:  00000000 3ffe97b7 feefeffe feefeffe  
3ffffcb0:  3ffffcac 4021e1c8 00000000 4021e1c8  
3ffffcc0:  00000000 4021e1c8 00000000 4021e1c8  
3ffffcd0:  00000000 4021e1c8 00000000 4021e1c8  
3ffffce0:  00000000 00000000 ffffffff 00000001  
3ffffcf0:  3ffea105 00000000 01001635 00000000  
3ffffd00:  00000000 3fff1c74 00000100 003f8000  
3ffffd10:  401057d8 3fff1b4c 402173b0 3fffefb0  
3ffffd20:  4010660d 3fff1c74 00000100 3fff1c74  
3ffffd30:  40215409 400042db 003f8000 402153fe  
3ffffd40:  00000000 00000000 0000001f 40104bf5  
3ffffd50:  4000050c 003f8000 3fff12c8 3fff1c60  
3ffffd60:  4000dd3b 00000030 00000014 ffffffff  
3ffffd70:  40002ef1 0275c281 00000013 0000028c  
3ffffd80:  3ffffed2 00000001 00000001 00000000  
3ffffd90:  00000000 00000000 0000001f 40104bf5  
3ffffda0:  4000050c 00000017 00000018 00000030  
3ffffdb0:  40202531 00000030 00000020 ffffffff  
3ffffdc0:  4020265a 00000013 00000004 60000318  
3ffffdd0:  c0036004 00000001 3ffeff44 fffffffe  
3ffffde0:  00000000 3fffc6fc 00000000 00000004  
3ffffdf0:  3ffe8644 00000002 3ffeff43 00000030  
3ffffe00:  0000001f 00000000 0000001f 3ffeffac  
3ffffe10:  00000031 0000000a 3ffeffac 3fff01b8  
3ffffe20:  00000010 00000010 00000000 40100579  
3ffffe30:  3ffffe6d 402165df 3ffffed0 00000001  
3ffffe40:  3ffeff66 00000000 00000000 40202725  
3ffffe50:  3ffeff66 00000068 3ffe874c 3ffeff18  
3ffffe60:  00000010 3fffff40 3fffff40 402165df  
3ffffe70:  3ffffec0 00000000 3fffff40 4021662b  
3ffffe80:  4024aff0 402165df 3fffff40 4021665d  
3ffffe90:  00000001 00000000 3fffff40 402166aa  
3ffffea0:  3ffffec0 00000000 3ffeff30 00000005  
3ffffeb0:  4020d9c0 3fffff40 3fffff40 4020d9c8  
3ffffec0:  00000000 3ffef9d8 3fff116e 40217ee9  
3ffffed0:  3fff118f 3f747ae1 3ffefa6c 3ffeff18  
3ffffee0:  00000000 00000015 3ffeffac 40215590  
3ffffef0:  3fff01b8 000002bd 000002bd 402158ad  
3fffff00:  3ffe9551 00000000 3fffff40 4021557b  
3fffff10:  40104d38 000ffd2a 3fff1d7c 00000000  
3fffff20:  3ffef6a0 3fff1d7c 00000014 401004e8  
3fffff30:  00000001 000b3876 4020fce4 3ffefecc  
3fffff40:  00000001 000003e8 00000000 4020fcc6  
3fffff50:  40209c14 00000001 00000001 4020fe05  
3fffff60:  cafebabe 00000001 3ffefef8 3ffefecc  
3fffff70:  3ffeff8c 3ffeff18 3ffeffac 4020cf46  
3fffff80:  feefeffe feefeffe feefeffe 00000000  
3fffff90:  feefeffe feefeffe feefeffe feefeffe  
3fffffa0:  feefeffe feefeffe feefeffe 3fff006c  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vbb28d4a3
~ld

FW 6.0.4
2.2.1(cfd48f3)
Worker run!
mounting FS... mounted!
scanning for OW device on pin: 5
No devices found!
scanning for OW device on pin: 12
No devices found!
scanning for OW device on pin: 116
No devices found!
scanning for OW device on pin: 121
No devices found!
ERROR: cannot find a OneWire Temperature Sensor!
Acc Test Connection ERROR!
Boot-Mode: Exception
...........
ERROR no Wifi credentials

going to Config Mode
reboot RFCAL

**Comment by vytux-com** [comment]
It's been noted before that this firmware will only work if everything is properly built and you seem to be missing the temp sensor so of cause it's not going to work.

BTW both versions are giving you the same error

**Comment by universam1** [comment]
Thanks for the comment, that’s indeed true and the case here. Hence we can close the issue

**Comment by brunoheins** [comment]
You're right, I did not read the notes. I'm sorry for this. Happy 2019 for everyone. Tks!!
