### ISSUE TITLE
iSpindel not working on battery power

### ISSUE THREAD

**Issue by xned** [universam1/iSpindel#249]
Not sure if this is good place to post this but I could not find any other English forums, feel free to refer me to a forum better suited for this issue.  

Background (feel free to skip to the problem part): 
I order the iSpindel kit from http://3D-Mechatronics.de, received it well packaged and with no visible damage to any components. 

I soldered the components according to the English soldering guide (https://brewlab.blog/wp-content/uploads/2017/10/DIY_Spindel_Anleitung_En.pdf) I don't think my soldering was any worse than it normally is so it should be okay. 

I did final assembly, powered trough the charging USB and flashed firmware trough the WeMos USB. That done I managed to connect to the iSpindel SSID, did basic config for WiFi, changed interval to every 20sec for testing and setup, created a ubidots account, put the token in the iSpindel config and looking at ubidots I can see that the iSpindel created a device and is sending data. 

The Problem: 
When disconnecting the USB to the charger the iSpindel dies. All diodes go dark and it stops reporting data. I Thought it might just be power saving (deep sleep) so I left if for a couple of hours, still no data. I'm not sure how the WeMos is powered but I saw someone mentioned the 5v pin so I took a multimeter to that and what I can see is that when the charger is connected to USB and everything is working I get about 4v on the 5v pin, running on battery it fluctuates from0,8v to 1,7v. Measuring directly on the battery I get 3,65V. 

Any idea what I'm doing wrong here? Or do I maybe have a bad battery or charging unit?

**Comment by universam1** [comment]
Probably the battery charging module is defect
