### ISSUE TITLE
failed to open config file for writing

### ISSUE THREAD

**Issue by Maettu99** [universam1/iSpindel#251]
Hallo 

Meine Ispindel sendet nur einmal und geht dann wider in den Config Mode weil sie die Einstellungen nicht Speicher kann. SIe sag: failed to open config file for writing.

Log:

         FW 6.0.4
2.2.1(cfd48f3)
Worker run!
mounting FS... ERROR: failed to mount FS!

ERROR config corrupted
scanning for OW device on pin: 5
No devices found!
scanning for OW device on pin: 12
Found device with ROM = 28 C3 9D EE 1F 13 1 2D
  Chip = DS18B20
  Data = 1 31 1 4B 46 7F FF C 10 4A  CRC=4A
  Temperature = 19.06 Celsius,
Boot-Mode: Deep-Sleep Wake

going to Config Mode
*WM: Scan done
*WM: Adding parameter
*WM: name
*WM: Adding parameter
*WM: sleep
*WM: Adding parameter
*WM: vfact
*WM: Adding parameter
*WM:
*WM: Adding parameter
*WM:
*WM: Adding parameter
*WM: tempscale
*WM: Adding parameter
*WM:
*WM: Adding parameter
*WM:
*WM: Adding parameter
*WM: selAPI
*WM: Adding parameter
*WM: token
*WM: Adding parameter
*WM: server
*WM: Adding parameter
*WM: port
*WM: Adding parameter
*WM: url
*WM: Adding parameter
*WM: db
*WM: Adding parameter
*WM: username
*WM: Adding parameter
*WM: password
*WM: Adding parameter
*WM: job
*WM: Adding parameter
*WM: instance
*WM: Adding parameter
*WM:
*WM: Adding parameter
*WM: POLYN
started Portal
*WM: SET AP
*WM:
*WM: Configuring access point...
*WM: iSpindel
*WM: AP IP address:
*WM: 192.168.4.1
*WM: HTTP server started
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Handle root
*WM: Skynet
*WM: -62
*WM: Pedro WLAN
*WM: -90
*WM: MQG-35546
*WM: -96
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: WiFi save
*WM: Parameter
*WM: name
*WM: iSpindel000
*WM: Parameter
*WM: sleep
*WM: 900
*WM: Parameter
*WM: vfact
*WM: 191.80
*WM: Parameter
*WM:
*WM:
*WM: Parameter
*WM:
*WM:
*WM: Parameter
*WM: tempscale
*WM: 0
*WM: Parameter
*WM:
*WM:
*WM: Parameter
*WM:
*WM:
*WM: Parameter
*WM: selAPI
*WM: 0
*WM: Parameter
*WM: token
*WM: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
*WM: Parameter
*WM: server
*WM:
*WM: Parameter
*WM: port
*WM: 80
*WM: Parameter
*WM: url
*WM:
*WM: Parameter
*WM: db
*WM: ispindel
*WM: Parameter
*WM: username
*WM:
*WM: Parameter
*WM: password
*WM:
*WM: Parameter
*WM: job
*WM: ispindel
*WM: Parameter
*WM: instance
*WM: 000
*WM: Parameter
*WM:
*WM:
*WM: Parameter
*WM: POLYN
*WM: -0.00031*tilt^2+0.557*tilt-14.054
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting wifi with new parameters...
*WM: previous settings invalidated
*WM: After waiting...
*WM: 4.00
*WM: seconds
*WM: Connection result:
*WM: WL_CONNECTED
saving config...
                need to format SPIFFS: 0
failed to open config file for writing
Samples:30 min:63.14 max:63.17 time:516
x: -9404 y: 12104 z: 2702
Tilt: 63.15
Tacc: 23.51
Volt: 4.09
Temp: 19.56
Gravity: 19.89
IP: 192.168.1.2

calling Ubidots
{"tilt":63.15175,"temperature":19.5625,"battery":4.092805,"gravity":19.8852,"int                                                                                                                                                             erval":1,"RSSI":-65}
                    Sender: Ubidots posting
POST /api/v1.6/devices/iSpindel000?token=xxxxxxxxxxxxxxxxx                                                                                                                                                             /1.1
Host: things.ubidots.com
User-Agent: ESP8266
Connection: close
Content-Type: application/json
Content-Length: 100

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 15 Jan 2019 19:54:29 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Vary: Cookie
Allow: GET, POST, HEAD, OPTIONS

d1
{"temperature": [{"status_code": 201}], "battery": [{"status_code": 201}], "tilt                                                                                                                                                             ": [{"status_code": 201}], "interval": [{"status_code": 201}], "gravity": [{"sta                                                                                                                                                             tus_code": 201}], "rssi": [{"status_code": 201}]}
0

Final-sleep: 1s; RT: 46204

Kann mir jemand weiterhelfen?
Gruss Matthias

**Comment by universam1** [comment]
Sieht wie ein krasser Hardware Fehler aus. Vermutlich musst du den Wemos ersetzen.
