### ISSUE TITLE
Unable to initial setup

### ISSUE THREAD

**Issue by bytepicker** [universam1/iSpindel#252]
I'm building my first iSpindel on @cherryphilip74 PCB v.3.1 
After flashing firmware 6.0.4 via USB and soldering the WEMOS module I can't see any WiFi called 'iSpindel'. 
Instead there is _sometimes_ active AP with the name "CleanMatefd:a6:bc". After connecting I can ping the module's IP, but that's all. Also I can't reflash the module - esptool refuses to connect to existing `/dev/ttyUSB0` device. Resetting doesn't help.
Being quite a newbie in ESP8266 I have no ideas what to do. Any help will be appreciated, thanks

**Comment by universam1** [comment]
You must be having issues to flash the device. There is some section in the docs, but in general I would think you did not install the drivers for yet
