### ISSUE TITLE
cannot enter derived formula

### ISSUE THREAD

**Issue by Pieter1954** [universam1/iSpindel#254]
When entering the formula derived from the calibration for calculating Plato and SG I encounter serious problems.
I start with f.i. 0.0000605064*(

after that I go to the device and choose Tilt. The purple icon is entered in the formula. From that moment on I cannot enter anything behind the Tilt icon to continue entering the formula.
If I enter other variables like Temperature or Battery it is possible entering things after the variable.

Who can be of help?

**Comment by universam1** [comment]
Fixed with 6.0.5. Please make sure to `reset` under `Maintenance` menu
