### ISSUE TITLE
Blynk support not working

### ISSUE THREAD

**Issue by tdsnor** [universam1/iSpindel#259]
Hi. 
Is the Blynk support released in 6.0.4? I was not able to choose this service in the drop down. But I see that Leo has been working with it.

Thanks.

**Comment by Grandement** [comment]
Hi,
I am waiting for this support as well. The pull request looks really promosing. I hope we get it soon into the Master.

**Comment by mr-bridger** [comment]
Is this in progress? I use blynk and would love to use that instead of ubidots.

**Comment by Grandement** [comment]
Hi mr-bridge,
I have compiled the pull request of Idab myself. Worked very good. I modified his version a little bit because I like Plato more than Gravity ;). Hopefully it will be merged to the master one day.

**Comment by ldab** [comment]
https://github.com/universam1/iSpindel/pull/264

**Comment by Topspliff** [comment]
Hi is there any update on this? I`m also a Blynk user and this would be most excellent to have it as an option, I gave up with Ubidots as I could not work out how to use it, I`m currently using the Thingspeak option, however, I do not get the gravity reading only temp, tilt and batt showing, no idea why any thoughts most appreciated.

Cheers Alan
