### ISSUE TITLE
Tcontrol port number is since V3.4.4 changed from 4968 to 80. Please change this back to port 4968

### ISSUE THREAD

**Issue by Henielma** [universam1/iSpindel#274]
The communication with Tcontrol does not work any more with version 6.0.6. The port number in the iSpindel software has been changed from 4968 to 80. Tcontrol uses for the iSpindel port 4968 can this be changed back as it was in version 3.4.4.

Hereafter the current code that uses the standard port

#ifdef API_TCONTROL
  if (service == DTTcontrol)
  {
    sender.add("T", scaleTemperature(Temperatur));
    sender.add("D", Tilt);
    sender.add("U", Volt);
    sender.add("G", Gravity);
    CONSOLELN(F("\ncalling TCONTROL"));
    return sender.sendTCONTROL(my_server, my_port);

**Comment by universam1** [comment]
solved with new v6.1.0
