### ISSUE TITLE
Ispindel sending data only after reset.

### ISSUE THREAD

**Issue by Khann007** [universam1/iSpindel#279]
Hello,
I have problem that my Ispindel send data only once, after that it does nothing at all.
Iam using resistor between d0 and rst tried 470ohm and 390 but no luck
Please look at log
Thank you
![er](https://user-images.githubusercontent.com/51379179/58899449-41c83b00-86fd-11e9-9775-053aea8c402e.png)

**Comment by Khann007** [comment]
Tried hotwiring rst to d0:
![er1](https://user-images.githubusercontent.com/51379179/58937232-159ad180-8772-11e9-91de-bad74df8458e.png)

**Comment by Khann007** [comment]
Replaced wemos d1 board with new one, now is working.

**Comment by Quernon** [comment]
Could you post a link to the board you have purchased? I'm having the same issue and have tried 3 different boards all with the same result!
