### ISSUE TITLE
Device will not reboot

### ISSUE THREAD

**Issue by Quernon** [universam1/iSpindel#281]
Firstly, thank you for all your ongoing efforts on this great project. 

I've been trying to get this to work for a while now but keep running into the same issue. I can configure the device to connect to my WiFi network and send data, and the data is correctly recorded. However, data is only sent once and only after pressing the reset button. After that, the device never wakes up again and never sends data.

I've looked at the serial log using putty. When the reset button is pressed it shows everything correctly. Then, after the time out, it just displays one line of unrecognisable characters and stops there.

I started with a resistor between RST and D0 but have changed that to a BAT43 diode (Cathode at D0) but the issue persists. I have now tried 3 different D1 Mini boards but all have had the same issue.

Looking at the regulator on the boards, it looks like they have the weak 150mA version. Could this be the cause? If so, do you know where it's possible to source boards which carry the correct regulator?

**Comment by universam1** [comment]
For testing short cut the RST and D0 and see if it changes. How about the voltage

**Comment by Quernon** [comment]
Do you mean that I should connect the RST and D0 pins directly, without the use of a diode or resistor? 

And where should I be measuring the voltage between? RST and D0?

Thanks for your help.

**Comment by Quernon** [comment]
Okay, so I've measured the voltage across D0 and RST. On first plugging in / turning on the D1 Mini it stays at a flat 0V. If I press the reset button it briefly flicks up to 1-2V but then stays at 0V thereafter.

If I hot wire the RST and D0 pins then the behaviour stays the same.

**Comment by Quernon** [comment]
I have ordered an official board from Wemos/Lolin's aliexpress page and will update this when it arrives. If there is anything else I should try in the meantime please let me know.

**Comment by universam1** [comment]
Yes short cut the RST and D0 to see if it’s about the resistor. Check that supply voltage is above 4V. If it is then still not working you got a hardware issue

**Comment by Quernon** [comment]
I tried shorting RST and D0 yesterday but it made no difference. I'll try a more robust short this evening (I was trying to avoid soldering anything when I last tried).

Pretty sure supply voltage was above 4V but I'll double check and get back to you. This would be measured across 5V and GND, correct?

**Comment by Quernon** [comment]
Shorting the RST and D0 pins made no difference. Supply voltage was >4V.

Looks like I have a hardware issue, probably due to the knockoff boards that I bought. I've ordered replacements and will update here when they arrive.

**Comment by trafim-uakraine** [comment]
I bought 5 esp8266 https://ru.aliexpress.com/item/Smart-Electronics-D1-mini-Mini-NodeMcu-4M-bytes-Lua-WIFI-Internet-of-Things-development-board-based/32659152063.html ? spm = a2g0s.9042311.0.0.31ad33edDinub0
Two weeks suffered and came to the conclusion that these boards are not compatible with deep sleep.
DOIT.AM is written on the WiFi module.
![2019-06-17_18-30-43](https://user-images.githubusercontent.com/51851714/59616983-29f5ab80-912e-11e9-97e2-50cf48a1a2e0.png)
![2019-06-17_18-34-46](https://user-images.githubusercontent.com/51851714/59617231-a12b3f80-912e-11e9-8106-9ec0537bb789.png)

**Comment by ErikdBr** [comment]
I use these: € 3,17 | LOLIN D1 mini V3.1.0-WEMOS WIFI Internet van Dingen development board gebaseerd ESP8266 4 mb MicroPython Nodemcu Arduino Compatibel
https://s.click.aliexpress.com/e/pbB4qQQZd

**Comment by Quernon** [comment]
@ErikdBr , those are the official ones from Wemos/Lolin so should be a safe bet. I've ordered the same.

**Comment by pamarovis** [comment]
Hello, have you got any news? I have the same mistake with sending data only once.
I bought this board : https://www.aliexpress.com/item/32845084675.html?spm=a2g0s.9042311.0.0.12e24c4dH0a1nj

**Comment by Quernon** [comment]
> 
> 
> Hello, have you got any news? I have the same mistake with sending data only once.
> I bought this board : https://www.aliexpress.com/item/32845084675.html?spm=a2g0s.9042311.0.0.12e24c4dH0a1nj

I'm still waiting for my replacement boards to arrive but will post here when they do.

**Comment by ErikdBr** [comment]
When you follow the D1 mini link on here http://www.ispindel.de/docs/Parts_en.html you go to https://wiki.wemos.cc/products:d1:d1_mini
On there click on th buy now button and you'll go to: https://nl.aliexpress.com/store/product/D1-mini-Mini-NodeMcu-4M-bytes-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266/1331105_32529101036.html

**Comment by pamarovis** [comment]
Can you see anything weird in my putty log? 

![tempsnip](https://user-images.githubusercontent.com/51999355/60208497-17cbe980-9861-11e9-8080-60c2d2d98193.png)

**Comment by pamarovis** [comment]
Ok, so i solved my problem ! The problem was with BAT43 diode soldered wrong way. Check yours ! :)

**Comment by Quernon** [comment]
Just confirming that the issue was with the clone board. Using the official one from Lolin has fixed the issue for me.
