### ISSUE TITLE
Ability to change MAC address?

### ISSUE THREAD

**Issue by BulletMag** [universam1/iSpindel#282]
I want to use several iSpindel in multiple brews, however I purchased five D1 mini clones from a Chinese seller and while they work it appears they all have the same MAC address so obviously I can't run them all at the same time.

Can a feature be added to change/spoof the MAC address so I can use these devices as I'm sure others will find this issue considering the amount of D1 mini clones out there.

**Comment by ErikdBr** [comment]
I could be wrong but I think when you flash the d1 with nodemcu flasher after you build your ispindel the software will assign a mac adress
![image](https://user-images.githubusercontent.com/48140503/61032824-7ac19280-a3c2-11e9-9214-930d2322205f.png)

**Comment by BulletMag** [comment]
Yes this is true, but i have five D1 minis that I have erased multiple times but when I go to flash them they all get the same AP MAC and STA MAC.
The five I mentioned above all came from the same reseller so likely from the same batch.
I have ten others from various other sellers all with completely different AP MAC and STA MAC so there  is clearly a possibility that the clones are literally that including the programmed MAC address.
My OQ refers to the fact that in the SDK there is a command 'wifi_set_macaddr' that allows the MAC address to be changed, unfortunately I do not know enough to know if this is permanent or per session hence why i asked if it could be added as a feature therefore if it was per session this could be done from the firmware.
