### ISSUE TITLE
Fairylink-#####

### ISSUE THREAD

**Issue by mossyrocks** [universam1/iSpindel#285]

**Comment by ErikdBr** [comment]
Well that clarifies it.

**Comment by mossyrocks** [comment]
Sorry erik,

I was having issues with the firmware but i downloaded 5.8 and it worked so i ttied to delete my question

**Comment by ErikdBr** [comment]
Yes I am having issues as well. Up until 5.8.6, I am fine, anything above that doesn't hold all the configuration data. But only some of us are having that issue.
