### ISSUE TITLE
Ispindel from localhost

### ISSUE THREAD

**Issue by JETET** [universam1/iSpindel#289]
Hello I open this post why I can not find information to access from localhost can you tell me something thanks

**Comment by stefschin** [comment]
You can use Breepi with a raspberry or Brewpiless to collect data locally, but from iSpindel you can just enter to configuration mode with Reset and it will give you instant data with an IP, but your battery wont last. 
Did you read iSpindle Documentation?

**Comment by JETET** [comment]
I would like to use this but I do not see any guide on the subject , do not need any more devices?
![Screenshot_2019-07-18-15-43-07-038_com android chrome](https://user-images.githubusercontent.com/44982343/61462540-1169f280-a973-11e9-8c15-58292a85602b.png)

**Comment by MTkeg** [comment]
I would start here:  [https://github.com/vitotai/BrewPiLess](url)

**Comment by JETET** [comment]
That link does not take me anywhere

**Comment by stefschin** [comment]
Just copy and paste in your browser `https://github.com/vitotai/BrewPiLess` or click here [Brepiless](https://github.com/vitotai/BrewPiLess)

**Comment by JETET** [comment]
Thanks, I'm going to try

**Comment by JETET** [comment]
Looks like I'm clumsy I've got the last of brePiless down, but it makes me wrong.
![Captura de pantalla 2019-07-18 20 31 09](https://user-images.githubusercontent.com/44982343/61482599-4c801c00-a99b-11e9-9fa2-821152247f6e.png)

**Comment by stefschin** [comment]
this is iSpindel topic, not Brewpiless

**Comment by JETET** [comment]
Okay, you know how to put the ispindel on localhost?

**Comment by stefschin** [comment]
> 
> 
> You can use Breepi with a raspberry or Brewpiless to collect data locally, but from iSpindel you can just enter to configuration mode with Reset and it will give you instant data with an IP, but your battery wont last.
> Did you read iSpindle Documentation?

I told you options you have, there is no localhost possible because iSpindel must save battery and can't be on all the time, it goes to sleep and every x intervals, take measurements, send data to a server and after that goes to sleep mode

**Comment by JETET** [comment]
what's the simplest thing?

**Comment by stefschin** [comment]
simplest thing is to use some made server, I use BrewSpy app

**Comment by JETET** [comment]
but it doesn't continuously update I now have it set to 5s and I don't see it being updated

**Comment by ErikdBr** [comment]
I also use the brewspy app. The minimum update frequency is 15s for a maximum of 2 hours for test purposes. After 2 hours it only accepts data every 5 minutes. But that is all in the documentation that can be found at brew-spy.com

**Comment by JETET** [comment]
Do you have the program in pro version?

**Comment by JETET** [comment]
you know if there is any free software and that it is full

**Comment by ErikdBr** [comment]
> Do you have the program in pro version?

Yes.

**Comment by ErikdBr** [comment]
> you know if there is any free software and that it is full

https://ubidots.com/education/

**Comment by JETET** [comment]
Good morning today I woke up and I found this message
![Screenshot_2019-07-21-07-44-52-872_com yiannnos myspindel](https://user-images.githubusercontent.com/44982343/61587601-7d27a780-ab8d-11e9-8a71-9ba03b681339.png)

**Comment by JETET** [comment]
I already found the fault is from my Internet line

**Comment by ErikdBr** [comment]
> Good morning today I woke up and I found this message

But you got the iSpindel working, very good!

**Comment by JETET** [comment]
everything ok ok I have to graduate it

**Comment by ErikdBr** [comment]
> everything ok ok I have to graduate it

That beer in you avatar, is that the Diablo Rojo? I would like the recipe :-)

**Comment by JETET** [comment]
Yes, send me a pribado, look what I took today to make a red devil tomorrow
![IMG-20190721-WA0005](https://user-images.githubusercontent.com/44982343/61589840-2b444900-abb0-11e9-9012-4f29a0373584.jpeg)

**Comment by ErikdBr** [comment]
> Yes, send me a pribado, look what I took today to make a red devil tomorrow

Unfortunately it is not possible to send private messages on github :-(

**Comment by JETET** [comment]
jetet34@gmail.com 
this is my e-mail
