### ISSUE TITLE
It is possible to use wemos D1 mini as a server to read ispindel data

### ISSUE THREAD

**Issue by JETET** [universam1/iSpindel#291]
It is possible to use wemos D1 mini as a server to read ispindel data

**Comment by universam1** [comment]
That is technically possible - however if it makes sense that is a different topic. There are number of server solutions already supported and can be referenced incase there is another new one.

**Comment by JETET** [comment]
I would like to see the information of an ispindel on this server seeing this information as it is shown by the original ispindel in this server code and to be able to see it in a browser by putting the ip that the wemos d1 mini provides when configuring it Thank you
![image](https://user-images.githubusercontent.com/44982343/66780425-10445500-eed1-11e9-981d-217fb066605f.png)

**Comment by JETET** [comment]
I don't know where to start This is the server
/SERVIDOR
#include <ESP8266WiFi.h>

const char WiFiClave[] = "";  //Sin clave
const char AP_Nombre[] = "Jopapa_ESP8266";

const int LED_PIN = 15; // LED rojo
int val;
WiFiServer server(80);

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);
  WiFi.mode(WIFI_AP);
  WiFi.softAP(AP_Nombre, WiFiClave);  
  server.begin();
}

void loop() {
  WiFiClient client = server.available();   // ¿Hay un cliente conectado?
  if (!client) { return;}
  String req = client.readStringUntil('\r');  // Lee la primera linea de la petición del cliente
  if (req.indexOf("/led/0") != -1) val=0;
  if (req.indexOf("/led/1") != -1) val=1;
  digitalWrite(LED_PIN, val); 
  client.flush();}

**Comment by JETET** [comment]
I don't want to save Nothing just to visualize
