### ISSUE TITLE
sanitary enclosure

### ISSUE THREAD

**Issue by mirceageorgescu** [universam1/iSpindel#292]
I love this project, built the kit and I'm thinking of trying it out in a large 7BBL stainless conical at the brewery. Not sure if wi-fi will penetrate through the stainless steel FV but we have a dry-hopping port where we could replace the cap with a plexiglass one.

Anyway, does anyone have a sanitary alternative to the petling? I imagine it's not easy to clean for reuse around the cap area.

I like the way Tilt solved the problem. Does anyone have some sketches to an alternative enclosure?

**Comment by ErikdBr** [comment]
> I imagine it's not easy to clean for reuse around the cap area.

It really is. After getting the tube out of my fermentation bucket I rinse it with water. Then I clean my bucket and the outside of the tube and lid as good as possible. I fill the bucket with a solution of water with a dishwasher tablet. I put all of my stuff used for fermentation in the bucket.
I dry the tube with a piece of paper towel. Then I turn the lid off with a paper towel to ensure nothing drips into the tube. I put the in the bucket with dishwater tablet solution.
I let everything soak for 24 hours.
Prior to next use I sanitize the inside and outside of the lid and the outside of the tube with ecolab.
![p3_alcodes_1000_ml_3](https://user-images.githubusercontent.com/48140503/62683848-b0589c00-b9bf-11e9-9a24-6b497b9daee8.jpg)
