### ISSUE TITLE
Minimalistic iSpindel tool

### ISSUE THREAD

**Issue by plut0nium** [universam1/iSpindel#294]
Hi,
Not an issue, but I  created a small GUI app that listen to iSpindel devices on the network (through TCP protocol) in order to quickly test and calibrate, without needing to create an account on Ubidots or similar, or to switch between multiple devices in configuration mode.

The reason for this is that I have to assemble and calibrate 10 iSpindels for my homebrewer association...

It is not meant for continuous fermentation monitoring.... there are plenty of other (better) apps or services available for this task.

Fell free to test and comment 🍻
https://github.com/plut0nium/iSpindelTool

**Comment by JETET** [comment]
thanks for the application but i don't know what i have to run on the pc thanks

**Comment by plut0nium** [comment]
This is a python app.
Just install python3 interpreter and run the *.py script.

**Comment by ErikdBr** [comment]
Thanks, I will use this nect time I have to configure an iSpindel.
