### ISSUE TITLE
iSpindel and Brewpiless setup questions

### ISSUE THREAD

**Issue by ebar03** [universam1/iSpindel#298]
Has anyone used a iSpindel in conjunction with Brewpiless? 
I have a question on how to use the iSpindel with Brewpiless and wondering how some one you set yours up.
Am I supposed to use the DS18 sensors from the Brewpiless with the iSpindel or just the iSpindel alone?
If I set the External Sensor (iSpindel) as Beer Temp, should I remove the other temperature device slots connected to the Brewpiless or keep one as Chamber Temp and change the other to Room Temp?
What reporting/interval period is best for the iSpindel? Wiki said nothing more than 5 minutes, but how will that affect battery life.

Appreciate the project and all the help.

**Comment by universam1** [comment]
This question is related to the other project, please post it there
