### ISSUE TITLE
Excel Plato Formel

### ISSUE THREAD

**Issue by scoobydo** [universam1/iSpindel#299]
Hi,
Can someone please explain the math behind the equation.
How does it make the calculation? How does it converts angle to plato.
Thank you

**Comment by plut0nium** [comment]
There is no real math magic behind it, this is a polynomial regression on the data you provide during the calibration.
During the calibration, you measure both density (using hydrometer/refractometer) and angle (reported by the iSpindel) and report it in the spreadsheet as a scatter plot (density as a function of angle). The sheet then uses the trendline function to fit a 3rd order polynomial to the data.

**Comment by universam1** [comment]
thank you for explanation
