### ISSUE TITLE
JSON library

### ISSUE THREAD

**Issue by fabian7791** [universam1/iSpindel#301]
HI!
What is the JSON library version? I can't compile because the error happens:

Foram encontradas múltiplas bibliotecas para "ArduinoJson.h"
Usado: C:\Users\v\Documents\Arduino\libraries\ArduinoJson
Não usado: C:\Users\v\Documents\Arduino\libraries\arduino_681333
Não usado: C:\Users\v\Documents\Arduino\libraries\arduino_536704
exit status 1
'DynamicJsonDocument' was not declared in this scope

Thanks!

**Comment by thedelisle** [comment]
VSCode and Platform.io will work nicely

**Comment by universam1** [comment]
you need to update your pio libs
