### ISSUE TITLE
MPU6050 files

### ISSUE THREAD

**Issue by sergioguimaraes** [universam1/iSpindel#311]
Are MPU6050.h and .cpp files missing for last release or are you using third part library for it?

**Comment by universam1** [comment]
Can you explain the issue?

**Comment by sergioguimaraes** [comment]
O could not find the files you used as .cpp and .h for the library MPU6050 for the last version. I am not sure if you forget to upload both or if are you using a third part library. The fact is that it can not be compiled without these files. Could you confirm the MPU6050 files are you using?

**Comment by universam1** [comment]
It does compile fine using platformio. See the latest change log
