### ISSUE TITLE
IP-address and MAC-address

### ISSUE THREAD

**Issue by mcmellow** [universam1/iSpindel#316]
How can I discover the IP-address and MAC-address of my configured iSpindel? 
In line with this. Can I assign a fixed or static IP-address to my iSpindel?

**Comment by ErikdBr** [comment]
Yes you can in the configuration of your router or accesspoint.

**Comment by mcmellow** [comment]
> Yes you can in the configuration of your router or accesspoint.
Thanks, that is the dynamic IP-address given by my router. Can I configure a static IP address in the iSpindel?

**Comment by universam1** [comment]
not supported, the IP reservation should suffice

**Comment by ErikdBr** [comment]
In my Zyxel router I can configure that a device gets a static ip from the router so no need to configure the device itself. It just gets the same ip from the router. Or am I not getting something here?

**Comment by mcmellow** [comment]
Thanks, I get it.  I will check this out.
