### ISSUE TITLE
New calibration

### ISSUE THREAD

**Issue by jpgimenez** [universam1/iSpindel#319]
I don't understand the new calibration routine, the image shows the battery down, if I make it that way I end up with a tilt of 62° on plain water and a gravity of 19... if I make it the other way around, battery up, I end up with a 20° tilt and gravity -3...
Something is missing on the docs?
Should I adjust the weight to read 0 on plain water?

**Comment by OpenSourceDistilling** [comment]
Did you do the offset calibration first before anything else?
