### ISSUE TITLE
can't calibrate - constant blue led

### ISSUE THREAD

**Issue by kestonikas** [universam1/iSpindel#321]
I just built iSpindel. Connected wifi, no issues. Updated firmware to latest (6.2.0). In maintenenace starting calibration - and here nothing happens, getting constantly blue led on.

Any suggestions?

**Comment by ErikdBr** [comment]
Check the FAQ here: https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md
and go to: "What should I do if my iSpindel isn't working properly after flashing it with the firmware?"

**Comment by Vadim1811** [comment]
when you compile iSpindel.cpp throws an error on line 24 (MPU6050 accelgyro;):
'MPU6050' does not name a type. How to fix?

**Comment by universam1** [comment]
thank you @ErikdBr
