### ISSUE TITLE
Tilt: 0.00°

### ISSUE THREAD

**Issue by sbonaime** [universam1/iSpindel#325]
Hi,

I just built my Ispindel with PCB 4.0 and Weemos D1 Mini V3.  With Firmware 5.8.6, I have 
Tilt: 0.00°
temperature: -127°

With telnet I have the following messages:

I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0

I understand than the lower chip which takes care of tilt and temperature can't connect through I2C. What can I check ? Thank you

![20191220_152240](https://user-images.githubusercontent.com/750709/71263907-33610a00-2343-11ea-900f-5fd1308f8594.jpg)
![20191220_152252](https://user-images.githubusercontent.com/750709/71263908-33610a00-2343-11ea-87b1-1f90ac01e405.jpg)

**Comment by sbonaime** [comment]
I did some wrong soldering on the Weemos ! Now It is working correctly
![20191220_161826](https://user-images.githubusercontent.com/750709/71264595-b898ee80-2344-11ea-9c49-17002d5b4557.jpg)

**Comment by langerc** [comment]
The wiring diagram is inconsistent the pins D3 and D6 have to be connected. In most manuals they are left out which results in
error can not load json
or the error above because it can not read the i2c bus.
