### ISSUE TITLE
How to use Service Type: HTTP

### ISSUE THREAD

**Issue by ps915** [universam1/iSpindel#333]
I can't find any documentation about the HTTP Service.

Is it possible to use it with my own HTTP Webserver?

What if i set up a .php script to log the data in a MySQL Database. 

http://beerserver.de/log.php?mode=iSindel_No_1&battery=4.15&gravity=39.9&interval=1&rssi=87.00&temp=22.5&tilt=82.5

Is this possible?

**Comment by mp-se** [comment]
Yes that is possible. The data will be sent as a http post and json format. This is an example of what you should expect in the request: 

{"name":"iSpindel002","ID":11795794,"token":"fermentrack","angle":46.20663,"temperature":17.625,"temp_units":"C","battery":4.160584,"gravity":11.02123,"interval":300,"RSSI":-85}

**Comment by ps915** [comment]
Thanks a lot, for the information, that's usefull! Is it somehow possible (or planned for the future) to support GET additional to the POST method?

**Comment by ps915** [comment]
How do i configure the Service correctly?

What does "token" mean?

![Screenshot_20200114-165110](https://user-images.githubusercontent.com/3420935/72359478-a5343580-36ee-11ea-8948-e82279fa2387.jpg)

**Comment by victorsoliveira** [comment]
@ps915 It's correctly! Token info is needed if your URI is authenticated token based, so, when you provide a token info when iSpindel make a POST at http://www.server.de/log.php an authorization header will be provided for request with this token information.

**Comment by ps915** [comment]
Ok, understand but unfortuantly i cant get it to work. 
I dont want to use the token at all so i leave it blank.

I configured the iSpindel in these two ways.

If i set up the Server Adresse like:
![Screenshot_20200114-172656](https://user-images.githubusercontent.com/3420935/72362752-03174c00-36f4-11ea-95d0-0230c77c6fb0.jpg)
the request URL looks good.
<img width="733" alt="1" src="https://user-images.githubusercontent.com/3420935/72362803-14f8ef00-36f4-11ea-8c51-56c27e94cc3d.PNG">


But if i configure it like this:
![Screenshot_20200114-172832](https://user-images.githubusercontent.com/3420935/72362753-03174c00-36f4-11ea-8b96-23985278e765.jpg)
The request does not go to the .php script, just to the main server.
<img width="733" alt="2" src="https://user-images.githubusercontent.com/3420935/72362804-14f8ef00-36f4-11ea-9b9c-444cbf7b10df.PNG">

I wrote this little PHP Script to test the Output of the iSPindel, but none of the both configurations create a POST Data.

When i test ist with my POST Form via HTML, everything works but just not with the iSpindel. Any idea what could be wrong?


<img width="306" alt="data" src="https://user-images.githubusercontent.com/3420935/72363362-0828cb00-36f5-11ea-866e-0156a9bee907.PNG">

`<?php

//check for Post data
if (!empty($_POST["data"])) {
	
	echo "Data received";
	file_put_contents("post.log", print_r($_POST, true), FILE_APPEND);

} 

//Show log
$log = file_get_contents('post.log');
echo "<pre>".$log."</pre>";


?>


<form action="http://server.de/logtest.php" method="post">
	<input type="text" name="data">
	<input type="text" name="data2">
	<input type="submit" value="SEND">
</form>`

**Comment by victorsoliveira** [comment]
@ps915 Try append a slash at "Path / URI" info... Use "/logtest.php" instead of "logtest.php"

**Comment by ps915** [comment]
i tried
Server Adress: **http://server.de/**
Path: **/logtest.php**

The iSpindel still just  makes a request to **http://server.de/** instead of **http://server.de/logtest.php**

**Comment by victorsoliveira** [comment]
When i configure it out, works fine with samples info below
**Server Address:** 192.168.0.105
**Path:** /ispindel

try to remove slashes and protocol from **Server Address** info

**Comment by ps915** [comment]
no sucess so far!  I tried to use it in my Local Area Network but same issue here.
I also tested it without the script path, so i created a index.php on my webserver.

tested this Server Adresses:

- 192.168.0.30
- http://192.168.0.30/
- http://192.168.0.30/index.php

**Comment by victorsoliveira** [comment]
@ps915 Yes, the POST data was transmitted.

Looking better now , you have a condition expecting POST BODY at "$_POST['data']", try without that condition, the JSON info from POST request come in at BODY.

Sou, try it out.

`<?php
//check for Post data

echo "Data received";

 $data = json_decode(file_get_contents('php://input'), true);
var_dump($data)

file_put_contents("post.log", print_r($data, true), FILE_APPEND);

//Show log
$log = file_get_contents('post.log');
echo "<pre>".$log."</pre>";

?>

**Comment by ps915** [comment]
dammit, totally my bad! I Fcked the $_POST['data'] up! I apologize and thanks you very much for your help! =) i owe you a beer!

**Comment by victorsoliveira** [comment]
Relax! @ps915.
Good beers for u!
