### ISSUE TITLE
Calibration issue

### ISSUE THREAD

**Issue by arjepsen** [universam1/iSpindel#342]
Hey.
I just put together an ispindel, using the ispindelpcb.
I'm having trouble getting the offset calibration done.
I can connect to the ispindel, and start the calibration - the blue diode lights up.... and stays on.
I tried waiting like 30 minutes, but it's still on solid. 
Any idea what I might have done wrong?

**Comment by ErikdBr** [comment]
Try the procedure "What should I do if my iSpindel isn't working properly after flashing it with the firmware?" in the FAQ: https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md

**Comment by ErikdBr** [comment]
> Hey.
> I just put together an ispindel, using the ispindelpcb.
> I'm having trouble getting the offset calibration done.
> I can connect to the ispindel, and start the calibration - the blue diode lights up.... and stays on.
> I tried waiting like 30 minutes, but it's still on solid.
> Any idea what I might have done wrong?

Did it work?
