### ISSUE TITLE
Angle to steep, to heavy battery

### ISSUE THREAD

**Issue by Naesstrom** [universam1/iSpindel#355]
I've managed to get most of my iSpindels to 23°-25° but in my last one I think the battery is a bit heavy so it sits at 18° in water. Will this still work or do I need to find a new battery? Tried adding weights to the lid but that didn't change anything other then how deep it was in the water :D

**Comment by ErikdBr** [comment]
Mine is also at 18 degrees in plain water, no problem.

**Comment by Naesstrom** [comment]
> Mine is also at 18 degrees in plain water, no problem.

Great, was worried when the FAQ says 25° +-5°
