### ISSUE TITLE
Wifi fix for latest firmware

### ISSUE THREAD

**Issue by kritjuu** [universam1/iSpindel#356]
I have a wifi issue. The wifi data is not updated to the server. 
I saw that there was a wifi fix for firmware 6.0.4. 
Is there also a fix for the latest firmware?

**Comment by Wicked-Creations** [comment]
I may have the same issue. I can access the iSpindel fine in config mode. But it won't send data. 

Wireshark reveals that the Wemos does an ARP request, but then no http activity.

**Comment by kritjuu** [comment]
Is there a solution. When I connect to Ubidots everything is fine. Data is send.
But when the server is http://community.grainfather.com no data is send.
Tried earlier firmware version (6.0.4)  but http adres is not saved. (software bug)
