### ISSUE TITLE
ispindel

### ISSUE THREAD

**Issue by james15071982** [universam1/iSpindel#363]
i have flashed with the bin file and now im not getting any signal on wifi so I tried reflashing it back to factroy restore and seeing if I got a signal but nothing PLEASE HELP

**Comment by ErikdBr** [comment]
Did you build the whole thing? Otherwise it will not work.

**Comment by thegreatgunbantoad** [comment]
Might be teaching granny to suck eggs here, but, you do know that once if has your WiFi credentials it will go to sleep and make up every 15 mins (configurable), to bring it out of that and serve it's portal you need to double tap the reset contacts/button.

**Comment by james15071982** [comment]
I did build the whole thing and have tried tapping the reset button and it still doesn’t work , the blue light just Flashes five times then goes off

**Comment by ErikdBr** [comment]
Try what is in the FAQ: https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md
where it says: "What should I do if my iSpindel isn't working properly after flashing it with the firmware?"

**Comment by kordi83** [comment]
James did you figure it out i have the same problem
