### ISSUE TITLE
Question: The scope or range of an iSpindel.

### ISSUE THREAD

**Issue by mcmellow** [universam1/iSpindel#366]
Dear Sam,

The iSpindel is original created to follow the fermentation of beer, I guess. I just wonder or the iSpindel is suitable for fermentation for a wider range of fermentations. What are the limits of the firmware?
I fermented  a water/sugar solution with a start SG 1.105 and an end SG 0,995  The angle went from 59.50° - 27.77° See attached picture
![ApparentAttentuation](https://user-images.githubusercontent.com/15740537/79216740-fd91e500-7e4d-11ea-8905-545aab15b67d.png)

**Comment by thegreatgunbantoad** [comment]
From the poly I have, it suggests that at 90 deg, so completely flat, the SG would be 1.194.  The reality is that as you approach either extreme you're going to start losing accuracy.
