### ISSUE TITLE
ISpindel stops working after about 3 Minutes

### ISSUE THREAD

**Issue by CBBC2020** [universam1/iSpindel#367]
I’ve built an iSpindle from a kit. Flashed using Nodemcu and all appeared fine. iSpindle appears on the network list and I can connect and configure it. ISpindel information is displayed ie. temp, tilt etc and the  Blue LED is flashing every second. After about 3 minutes the LED flashes brightly once and the iSpindle disappears from the network list. Pressing reset kicks it off again but then stops in the same way. Help anyone.

**Comment by mcmellow** [comment]
What value is your timer interval set?

**Comment by CBBC2020** [comment]
Hi, I take it you mean the interval for sending data to Brewfather, this is set at 900 secs.

**Comment by mcmellow** [comment]
So it is not getting awake after the first interval (900 sec).  It is earlier.  Did you check all soldering and are all the components are mounted correctly.  You could check this side https://www.esp8266.com/

**Comment by CBBC2020** [comment]
It is only running for 3 minutes and then stops. I would assume that if any of my circuitry is wrong then I would not be able to flash and it wouldn’t run at all.

**Comment by CBBC2020** [comment]
Ah, didn’t see the last bit of your reply. I will check.

**Comment by mcmellow** [comment]
See closed issue #343  
My iSpindle worked correctly once and fell in a deep sleep. Only switch on and on trigged once. Cause a incorrect mounted diode. Mounted it correctly and soldered again. It worked like a charm. When the wemos board is OK, but the connections or components on the mainboard are not correct. You are able to flash, but working can give unpredictable results.
Success with the checking

**Comment by CBBC2020** [comment]
I’ve disconnected the circuitry from the Wemos and it is doing exactly the same thing. I’ve down loaded Putty and run it on Com 3 but I don’t really know what the output is telling me. The first image is when it’s running and outputs every time the LED blinks. The second is when it stops!

![5B625AD2-7C90-411F-BA08-9A464A2AD1E3](https://user-images.githubusercontent.com/63588734/79563738-41caf280-80a5-11ea-9793-173b8cf1cef9.jpeg)

![7D9425B5-6732-4625-81A8-314E4A33D946](https://user-images.githubusercontent.com/63588734/79563808-632bde80-80a5-11ea-91eb-eb4c8ed638d9.jpeg)

**Comment by mcmellow** [comment]
You have disconnected the Wemos. When you did flash your Wemos, did you do this with clear all memory first?
Sorry, can not make any sense of your screenprints.

**Comment by CBBC2020** [comment]
I know, just looks like rubbish. Yes I flashed Wemos to clear all memory first as I thought it looks like it is running out of memory then stopping. Thanks for your interest and feed back. I wait in hope that someone out there has had the same problem and knows how to fix it.

**Comment by mcmellow** [comment]
Just check my 2 iSpindels.  This looks your configuration file is not loaded (or present) because nothing happens. No worker started.Atleast you should see somthing started with this:

![iSpindel-Monitor](https://user-images.githubusercontent.com/15740537/79641566-9d29dd00-8198-11ea-96a4-ffcedb0534ca.png)

Do a configuration, ie just the time interval or so and make sure you hit the save button and wait until it is fully saved.
Or start with a new flash of the latest firmware 6.2.0 or later with a wipe of all data.  And do an configuration after the new flash.

Success

**Comment by CBBC2020** [comment]
Being very much a novice at this, I have come to the conclusion that the iSpindel is actually working correctly. It is simply going into sleep mode after a few minutes and then attempting to sent data at every set interval. The problem I now have is that I am trying to sent data to Brewfather and it is not connecting. Have uploaded a screen shot so any help would be appreciated.
![BE5218F3-A0FF-4717-8348-EB8CE969D438](https://user-images.githubusercontent.com/63588734/79644289-e9c4e680-819f-11ea-8ab1-5855fbd92fa9.jpeg)

**Comment by mcmellow** [comment]
As far as I can see it is working correctly. About the connection to Brewfather, I know nothing. Have look at the brewfather site for this.

**Comment by universam1** [comment]
Clearly the log says „failed to connect “ so your server is not reachable
