### ISSUE TITLE
MQTT Topic? 

### ISSUE THREAD

**Issue by petheridge** [universam1/iSpindel#369]
Can anyone tell me what topic the iSpindel uses when publishing over MQTT? Can see it connected to the broker at the correct interval but cannot figure out the Topic. Any pointers much appreciated!

**Comment by jmelhus** [comment]
Derived from source code:

ispindel/NAME/KEY

Where NAME is your preconfigured ispindel name. Key is the different parameters sent: tilt, temperature, temp_units, battery, gravity, interval and RSSI (ref https://github.com/universam1/iSpindel/blob/1d1c8606bf1909e408a95585780e1f53ca03a53b/pio/src/iSpindel.cpp#L561 )

**Comment by petheridge** [comment]
Got it working. Thanks!
