### ISSUE TITLE
Part replacement

### ISSUE THREAD

**Issue by mnandres** [universam1/iSpindel#375]
Hi, I have a few questions about replacing parts.

I can't get the diode bat43, is it the same to use the resistance?

Speaking of resistance, in the project they use a 220k resistance but I saw on other websites that they use 230k or 330k.
Which one is correct?

For the tp4065 case, did I get the Batery shield charger wemos? can be used, does anyone use it?

I also have doubts with the accelerometer, here you get the 3-axis GY-521 and the 6-axis MPU6050, which would be the one?

Finally I got a shiel from wemos with the ds18b20, which includes a resistor but I can't see what its value is.
Anyone use it? do I need to add the 4k7 resistor?

thank you very much and sorry for my english

**Comment by stefschin** [comment]
> 
> 
> Hi, I have a few questions about replacing parts.
> 
> I can't get the diode bat43, is it the same to use the resistance?
> 
330 Ohm or BAT43 Diode

> Speaking of resistance, in the project they use a 220k resistance but I saw on other websites that they use 230k or 330k.
> Which one is correct?
> 
It's for Battery voltage measurement and you have to calibrate it, so you can use 220K or 230K, I didn't see 330K

> For the tp4065 case, did I get the Batery shield charger wemos? can be used, does anyone use it?
> 
I don't know

> I also have doubts with the accelerometer, here you get the 3-axis GY-521 and the 6-axis MPU6050, which would be the one?
> 
GY-521 it's code for Arduino module, who has MPU6050 - 3 axis accelerometer and 3 axis Gyroscope= 6 axis

> Finally I got a shiel from wemos with the ds18b20, which includes a resistor but I can't see what its value is.
> Anyone use it? do I need to add the 4k7 resistor?
> 
I don't think so, values between 3.3k and 10k should work

> thank you very much and sorry for my english
