### ISSUE TITLE
Ubidots alternative

### ISSUE THREAD

**Issue by guilleiwd** [universam1/iSpindel#376]
Hi every one. A pleasure to join.
I have a doubt. There is any alternative to ubidots to check the fermentation and other data. Because ubidots told me something about my maximum dots per day and I don't get new information. Kind regards.

**Comment by thegreatgunbantoad** [comment]
Brewfather rules.  It's not free but it is fairy cheep.

**Comment by thegreatgunbantoad** [comment]
Brew spy is free, but it's a bit meh

**Comment by ErikdBr** [comment]
I sur brewspy and it's great! But it is an app on your phone and is not free.
![Screenshot_20200513-221440_BrewSpy](https://user-images.githubusercontent.com/48140503/81860612-492bd180-9567-11ea-9f35-5cdabc65e3eb.jpg)

**Comment by guilleiwd** [comment]
Thanks very much for the comments mates. I will check both. A big hug from Spain!!

**Comment by petjez** [comment]
Hey. I use monitor.beer. It's a free website and just simple to use.

Patrick

**Comment by guilleiwd** [comment]
I will check it as well!  Thanks mate!!
