### ISSUE TITLE
Cannot access 192.168.4.1

### ISSUE THREAD

**Issue by sikret1337** [universam1/iSpindel#378]
Good day,

I faced problem with connecting with 192.168.4.1. I flashed the Wemos D1 Mini then I connected to the ESP8266 AP (name is differ than iSpindel by the way) and I cannot access 192.168.4.1. 

I am able to ping 192.168.4.1 -t and ESP8266 responding.

Can You give me and guides how to fix my problem?

**Comment by ErikdBr** [comment]
Did you build the whole thing?

**Comment by sikret1337** [comment]
Good day,

I build everything on the contact plate except ds18b20 temp sensor

W dniu pon., 18.05.2020 o 19:07 Erik <notifications@github.com> napisał(a):

**Comment by sikret1337** [comment]
W dniu pon., 18.05.2020 o 19:07 Erik <notifications@github.com> napisał(a):

**Comment by sikret1337** [comment]
https://imgur.com/a/6P0LMro

**Comment by ErikdBr** [comment]
Everything needs to be attached.

**Comment by sikret1337** [comment]
@ErikdBr 

Thanks for this tip - problem fixed.
