### ISSUE TITLE
6.3.0 still calls itself 6.2.0

### ISSUE THREAD

**Issue by gingerneil** [universam1/iSpindel#387]
Looks like the changes from 6.3.0 have been merged, but 6.3.0 still reports itself as 6.2.0 on the console output and in the web config. Not sure where this needs updating ??

**Comment by thegreatgunbantoad** [comment]
@gingerneil It's in pio>lib>Globals.h line 23

**Comment by gingerneil** [comment]
Yep - still in as 6.2.0

**Comment by gingerneil** [comment]
Added a PR to fix - should be a fairly quick review! :)
