### ISSUE TITLE
firmware 6.3.0 reporting as 6.2.0

### ISSUE THREAD

**Issue by jonnygoldengonads** [universam1/iSpindel#390]
Hi there. When flashing with 6.3.0, the web console is reporting the version as 6.2.0, seems to be here in pio/lib/Globals/Globals.h. Apologies if I'm missing something, I'm quite new to this.

// defines go here
#define FIRMWAREVERSION "6.2.0"

**Comment by universam1** [comment]
Thanks, fixed that with https://github.com/universam1/iSpindel/releases/tag/6.3.1
