### ISSUE TITLE
Reported battery voltage not changing

### ISSUE THREAD

**Issue by frankr1977** [universam1/iSpindel#394]
Hello,

The battery voltage reported by my ispindel is not changing and is much too high. The measured voltage at pin A0 is ~3.7V but ~5.4V is being reported. I have a 220ohm resistor between Vcc and pin A0.

thanks,

Rich

**Comment by thegreatgunbantoad** [comment]
That should probably be a 220k.  So you'd be a factor of thousand out.

**Comment by frankr1977** [comment]
Dang it, you're right! Just looked at the circuit diagram again!

Thanks!!
