### ISSUE TITLE
Button zum "History löschen"

### ISSUE THREAD

**Issue by JensW2000** [universam1/iSpindel#4]
Das Config Menü (captive Portal) könnte einen Button zum Löschen der Historydaten bei UbiDots & Co. bekommen, damit man bei neuen Gärungen mit einem leeren Verlauf anfangen kann.
UbiDots stellt dafür z.B. eine DELETE API zur Verfügung.

**Comment by universam1** [comment]
Konzeptionelles Problem dass man im CP keinen Internet Zugriff hat. 
Man könnte evtl. ein Flag setzen für den nächsten reset im normal Mode, wenn du Lust hast kann du das ausarbeiten?

**Comment by universam1** [comment]
Edit: man kann das sogar in der aktuellen Session machen, da man nach dem CO direkt in normal Mode kommt! Top!

**Comment by JensW2000** [comment]
Das Löschen baue ich gerne ein. Ich versuche mal ob ich es hinbekomme. 

Konntest Du den Merge Request jetzt lesen?

 

Gruß

Jens

 

Von: universam1 [mailto:notifications@github.com] 
Gesendet: 27. Nov. 2016 15:59
An: universam1/iSpindel <iSpindel@noreply.github.com>
Cc: Jens Warkentin <jw@innovasoft.de>; Author <author@noreply.github.com>
Betreff: Re: [universam1/iSpindel] Button zum "History löschen" (#4)

 

Edit: man kann das sogar in der aktuellen Session machen, da man nach dem CO direkt in normal Mode kommt! Top!

**Comment by universam1** [comment]
Decided this have to happen in higher logic than firmware.
