### ISSUE TITLE
Connection to Fermentrack

### ISSUE THREAD

**Issue by worgz01** [universam1/iSpindel#401]
## Report

I am having issues continuing to fermentrack. I thought it was the fermentrack but I have exhausted that line of attack

![image](https://user-images.githubusercontent.com/67539683/86913460-4a394380-c151-11ea-9f78-17019264cd7f.png)

I have had one success in connection after I improved the network strength but them no movement in data readings after that.

It does however connect successfully to UBIDOTS with no problem

I have configured correctly, I think, but cannot get any connection data to fermentrack
![image](https://user-images.githubusercontent.com/67539683/86914108-4eb22c00-c152-11ea-8382-7b659c47f5c8.png)

**Comment by brendongough** [comment]
Path/URL looks wrong, try making it http://192.168.0.17/ispindel

**Comment by worgz01** [comment]
Sorry, I tried what you suggested, as indicated in the first file snip. The second file was a previous snip before i changed the path setting. My bad.

![image](https://user-images.githubusercontent.com/67539683/87304778-ee532e00-c547-11ea-8b9f-45b0d1dae0eb.png)
