### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by worgz01** [universam1/iSpindel#402]
Second build and another issue, I have offset calibrated successfully (89.5 degree) but went to check 25 degree and indication were way off at 52.5 degree. When i took the iSpindel out of the water and suspended it vertically, the tilt angle was 42 degree, which I assume it should be near 0 degree when vertical. Tried re-setting, re-flashing, re-calibrating the offset. No improvement

 Would it be safe to say that the Gyro is a shot duck!

**Comment by thegreatgunbantoad** [comment]
Almost certainly.  I've seen similar.  The gyros are very prone to being naff.

**Comment by worgz01** [comment]
OK, changed the Gyro. 
I then went into configuration mode to do offset calibration. The angle was reading 86.4 degrees, so OK I'll have to offset cal.
I thought,  I'll see what the angle was in water (SG 0.000) before offsetting. Reading was 22.7. 
Excellent I thought, if the offset calibration moves to the 89.5 degrees, the angle at 0.000 gravity should be very close to 25 degrees. OK
Carried out the offset, checked the 0.000 gravity and low and behold, I'm back to the same issue. :-(

When I grab the device (out of water) and rotate it from horizontal through a rotation of approximately true 120 degrees, then I get readings of 25 Degrees.

Surely this is something other then the Gyro????

**Comment by sirtomwwatts** [comment]
I was about not post an almost identical issue. Slightly different numbers but basically I can't get my gyro to go close to vertical
![This gave a tilt of 89.5 which I think is ok](https://user-images.githubusercontent.com/47772771/87541309-f40c5900-c698-11ea-9b75-d6f866b62abd.jpg)
![Held at about 60 gave a reading of 83](https://user-images.githubusercontent.com/47772771/87541311-f53d8600-c698-11ea-95ab-f43316872372.jpg)
![basically virtical gave a value of 64.41](https://user-images.githubusercontent.com/47772771/87541312-f5d61c80-c698-11ea-8b9f-7c87147cf458.jpg)

I'm using firmware 6.2.0, I don't have another gyro so would like to rule out hardware before I buy another

**Comment by ErikdBr** [comment]
Did you try laying it flat on a table exactly as you did doing the offset calibration but then roll it over 180 degrees and then do the offset calibration?
I read somewhere on here that some of the builds, and there are several different boards with and without battery holder and the like, the gyro needs to be "upside down" when doing the offset calibration.

**Comment by worgz01** [comment]
Yes, followed the directions as stated in #340 with no luck at all. Have done a factory reset, re-flash and offset (with the Gyro upside down) with no luck. Even tried with the GYRO in the vertical plan :-)
It just strange how it was close to the required angle of 25 degree in 0.000 SG before I did the offset calibration

**Comment by thegreatgunbantoad** [comment]
Some of the gyros out there are just rubbish and only good for the bin.  Same can be said of the Wemos boards (most of which are clones).  Occasionally the temp sensors are duff too.  If you can, test everything before you solder i down.
