### ISSUE TITLE
Possibility to "flip" gyro orientation

### ISSUE THREAD

**Issue by mike-van-e** [universam1/iSpindel#403]
Hi all,

Would it be possible to change the code so that there's an option to "flip" the values of the Gyro, right now my gyro is facing down when the iSpindel is in it's resting position on my desk.
I know that the documentation tells you to have the Gyro facing up when the iSpindel is in it's resting position, but for technical reasons i wasn't able to mount it this way.

I can circumvent it right now by calibrating my iSpindel while having it "bottom-up", but as you can imagine this is not really accurate since gravity is not helping me find the exact resting position of the iSpindel.

Thanks,

Mike.

**Comment by pep62** [comment]
I probably have the same issue with the one I bought : would that mean your tilt is around 60° on pure water instead of 25° ?
