### ISSUE TITLE
iSpindel Kick

### ISSUE THREAD

**Issue by grahambayley** [universam1/iSpindel#406]
Hi All

Getting a strange effect from my Second Spindel, its done this for 4-5 brews now .... 

Pop in the spindle, get a low reading, then it jumps in SG. you can see from the attached image. When I Calibrate its spot on and water cal gives 23.4 deg for 1.000 SG @ 22 Deg C

Any Ideas ???

<img width="1590" alt="iSpindel kick" src="https://user-images.githubusercontent.com/6314439/88278841-68449d80-cd26-11ea-8ce7-4d402b26f59a.png">

**Comment by ldab** [comment]
It happens with me when i move the fermenter, my theory is that the iSpindel moves inside the fermenter and touches the wall, consequently changing its tilt.
