### ISSUE TITLE
QR code for Blynk application is broken on iOS

### ISSUE THREAD

**Issue by isaul32** [universam1/iSpindel#417]
## I'm submitting a ...
  - [x] bug report

## Report

QR code for Blynk application is broken on iOS.

## Steps to Reproduce (for bugs)

1. Touch the QR-code icon and point the camera to the code below
2. Receive "This is not a valid Blynk QR code" message

## Context

Instead I have to build my application from scratch.

## Your Environment

- Blynk iOS app version used: 2.26.5

**Comment by ldab** [comment]
It works on my Android. The following configuration is used for the record:

<img src="https://user-images.githubusercontent.com/34199302/91145617-09bc6780-e6b6-11ea-89c6-fae9a6f3317e.png" width="35%" />

**Comment by isaul32** [comment]
I managed to create an interface now. So, maybe it was some temporary problem or user error.
