### ISSUE TITLE
Unable to Save Polynominal 

### ISSUE THREAD

**Issue by Takatu** [universam1/iSpindel#421]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please note that this repositories issues are intended for feature requests and bug reports.

## Did you follow the general troubleshooting steps first:

- [x] Follow through the [FAQ](https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md) ?
- [x] Checked the logs for errors in the terminal console ?
- [x] Searched for [similar reports already](https://github.com/universam1/iSpindel/issues) ?

## Report

I used the iSpindel configuration page to generate the Polynominal for my iSpindel configuration. I'm able to enter the result `0.9010787526325456 + 0.006500930269880398 *tilt-0.00011969987771509302 *tilt*tilt + 9.137856556348075e-7 *tilt*tilt*tilt` in the configuration screen but when I apply the configuration it is not saved. 

With first degree `0.9624376004722526 + 0.0016498481733399368 *tilt` it's working and it is getting saved. 

iSpndel calibration page: http://www.ispindel.de/tools/calibration/calibration.htm

## Steps to Reproduce (for bugs)
1. Boot the iSpindel in configuration mode
2. Enter configuration
3. Set Polynominal to: `0.9010787526325456 + 0.006500930269880398 *tilt-0.00011969987771509302 *tilt*tilt + 9.137856556348075e-7 *tilt*tilt*tilt`

In the log output when saving is still the pre set formula from the firmware.
<\n>saving config...<\n>{"Name":"iSpindel000","Token":"BBFF-v2hihh2UE5XNMXf8rBic4X86pNNhus","Sleep":900,"Server":"","API":0,"Port":80,"Channel":0,"URI":"","DB":"ispindel","Username":"","Password":"","Job":"ispindel","Instance":"000","Vfact":191.8,"TS":0,"OWpin":12,"POLY":"0.9010787526325456 + 0.006500930269880398 *58.68-0.00011969987771509302 *58.68*58.68 + 9.13785655634000","SSID":"xxxx","PSK":"xxxxx","Offset":[-4538,-1608,328,-93,-31,-9]}<\n>saved successfully<\r>

Related issue: https://github.com/universam1/iSpindel/issues/379

## Context
Saving configuration with third degree poly from calibration webpage

## Your Environment
- Firmware Version used: 6.3.1
- Browser Name and version: Mobile Chrome latest version
- Service backend you have configured the iSpindel to talk to: Ubidots

**Comment by thegreatgunbantoad** [comment]
Three things, 1 your poly is too long (100 character limit).  2 use some brackets. 3 remove spaces (they can cause it to be buggy)  

Try:  0.901078752632+(0.00650093026988*tilt)-(0.000119699877715*(tilt^2))+(9.13785655634e-7*(tilt^3))
