### ISSUE TITLE
Wemos not starting AP

### ISSUE THREAD

**Issue by mc1893** [universam1/iSpindel#427]
Hi,
I'm trying to get the code running on the WEMOS, so I flashed the newest firmware to it and monitor the output via Arduino IDE.

```
FW 6.3.1
2.2.2-dev(38a443e)
Worker run!
mounting FS... mounted!
ERROR: failed to load json config

ERROR config corrupted
scanning for OW device on pin: 5
No devices found!
scanning for OW device on pin: 12
No devices found!
scanning for OW device on pin: 116
No devices found!
scanning for OW device on pin: 121
No devices found!
ERROR: cannot find a OneWire Temperature Sensor!
offsets not available
Boot-Mode: Deep-Sleep Wake
...........
ERROR no Wifi credentials

going to Config Mode

Exception (28):
epc1=0x40209c1f epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
```
So far, I only connected the WEMOS to the GY-521 (DS18b20 is ordered). Is this then supposed to happend? So the Wemos does not open an access point if no temperature sensor is connected?

Thanks for helping!

**Comment by ErikdBr** [comment]
You need to build it completely, otherwise it won't work.
