### ISSUE TITLE
Weight

### ISSUE THREAD

**Issue by JohnnyGunn** [universam1/iSpindel#43]
Hi again,

One question about weight in the tube. What are you using for weight and how much?

Thanks.

**Comment by universam1** [comment]
That is _absolutely_ dependent on your the volume of the preform case!
I can only give hints to the preform I reference in the doc. There the overall weight is at 200g. I use angler lead in epoxy to glue it to the bottom, about 10g. Test beforehand how much you have to add for the case to be tilting with 25° when in normal water.

**Comment by christoferjh** [comment]
Tilt 25° from water line (horizontal) or from pointing straight down?

**Comment by JensW2000** [comment]
25° measured iSpindel (GY-521) tilt value.

**Comment by liuto-attiorbato** [comment]
Which is 25 deg from vertical.
