### ISSUE TITLE
Sourcing of the XL Petlings in Germany for fitting insert? Do 21700 batteries fit inside?

### ISSUE THREAD

**Issue by DrBabbage** [universam1/iSpindel#437]
Hi,
Unfortunantely http://cachers-world.de/de/Petling-XL cachers world is now cache-corner and they claim their petling is not made for brewing https://www.cache-corner.de/rohrabdeckung-mit-xl-petling.html. Does it still work? It looks so small :(
Does anyone know a shop where I can print a fitting insert?

Did anyone tried to put 21700 batteries in there?

Thanks!

**Comment by ErikdBr** [comment]
These are the ones I am currently using with the original design: https://adventure-caching.de/cache-behaelter/mikro-behaelter/233/mikro-behaelter-giantpet-riesen-pet-rohling-15-cm-x-4-cm
