### ISSUE TITLE
Blynk - ISpindel sending rounded specific gravity value

### ISSUE THREAD

**Issue by MatthBou** [universam1/iSpindel#442]
Hello,

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request

## Report
The problem happens when data are sending to Blynk and using the specific gravity.

The specific gravity value is rounded only two digits after the decimal point, which takes away from the precision.
for example :
- specific gravity read by the iSpindel: 1.052
- specific gravity sent to blynk: 1.05

## Solution
Round gravity value 3 digits after decimal point :
sender.add("4", String(Gravity, 3));

Many thanks

**Comment by nafraga** [comment]
excuse me , but this string where would be added ? by putty directly in ispindel ? i have the same problem with blynk ,but  i'm not an expert

**Comment by MatthBou** [comment]
@nafraga this line must be modified in the iSpindel.cpp file, line 699

**Comment by nafraga** [comment]
and where i find it ? if i dowload the firmware and the source code i don't  see .ccp file

**Comment by nafraga** [comment]
can change it directly in my ispindel by serial command ? or i have to download the source code ,change the.ccp file and then? thanks

**Comment by MatthBou** [comment]
@nafraga no you can't by serial command. Give me your email i send you a modified .bin

**Comment by nafraga** [comment]
nobis81.mn@gmail.com         thanks .  which program you use to modify .bin file?

**Comment by ErikdBr** [comment]
> @nafraga no you can't by serial command. Give me your email i send you a modified .bin

I suggest you read https://github.com/universam1/iSpindel/blob/master/LICENSE before sending a modified bin

**Comment by ErikdBr** [comment]
> [nobis81.mn@gmail.com](mailto:nobis81.mn@gmail.com) thanks . which program you use to modify .bin file?

You have to alter the sourcecode and then compile it into a bin. Don't know which tools they use for iot .cpp.

**Comment by nafraga** [comment]
sorry

**Comment by MatthBou** [comment]
> 
> 
> > @nafraga no you can't by serial command. Give me your email i send you a modified .bin
> 
> I suggest you read https://github.com/universam1/iSpindel/blob/master/LICENSE before sending a modified bin

oups sorry

**Comment by nafraga** [comment]
sorry too

**Comment by nafraga** [comment]
but can i say the program to compile the (c++?) file into .bin?

**Comment by MatthBou** [comment]
> 
> 
> but can i say the program to compile the (c++?) file into .bin?

Visual Core Studio and platformio

**Comment by nafraga** [comment]
thank you

**Comment by MatthBou** [comment]
Solved by  #449
