### ISSUE TITLE
The diode on the board is not needed

### ISSUE THREAD

**Issue by jsbjx** [universam1/iSpindel#447]
After consulting the data, in SLEEP mode, just short-circuit RST and D0 directly. There are short circuit points on the D1 mini V3.0.0 board. After testing, all functions are normal.
![55409c4fc5c005fdd7621726da65eed](https://user-images.githubusercontent.com/32890201/102712691-f89b0480-42fd-11eb-9c4c-f6a0607a3ec8.jpg)

**Comment by universam1** [comment]
D0 can be pulled up by the MCU while pulled down by the usb serial chip which might overload the GPIO. If you don’t care about the hardware you can short circuit
