### ISSUE TITLE
Add a README.md to explain the purpose of the different drawer designs

### ISSUE THREAD

**Issue by dsvensson** [universam1/iSpindel#45]
Add a README.md to explain the purpose of the different drawer designs found here:

https://github.com/universam1/iSpindel/tree/master/drawer

Drawer-cachersworldXLv12.stl has a version number, and the highest, but Drawer-combo-short.stl was most recently changed. They look slightly different while Drawer-cachersworldXLv12.stl and Drawer-cachersworldXLv11.stl are indistinguishable to me. Some description is in place.

It looks like the kit here:
https://3d-mechatronics.de/en/ispindel-diy-set-komplett_151.html

Has either Drawer-cachersworldXLv11.stl or Drawer-cachersworldXLv12.stl

**Comment by dr3x** [comment]
![ispindle_sled](https://cloud.githubusercontent.com/assets/829901/24472235/da29c8a8-1479-11e7-9915-4ca2928273a6.jpg)

The sled is slightly too large for the Ebay container that I bought; image shows how far it goes before it jams.  

**XXLBIG PET Micro Geocaching container geocache Petling preform Soda bottle FTF**
[http://www.ebay.com/itm/142295113730?_trksid=p2060353.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT](url)
https://raw.githubusercontent.com/universam1/iSpindel/master/drawer/drawer-combo-short.stl

**Comment by universam1** [comment]
Thats indeed the tough part, finding a suitable container.

But here is the trick, put the sled into hot water ~140°F where it gets soft, then push it gently into the sled. Repeat it if necessary, you will squeeze it until it fits. 
Not perfect but works!

-Sam

**Comment by dsvensson** [comment]
So based on the above comments this is the only one that should remain in that directory:

https://raw.githubusercontent.com/universam1/iSpindel/master/drawer/drawer-combo-short.stl

and the other ones should be deleted? Is that correct @universam1 ?

**Comment by universam1** [comment]
Yeah I know, maybe I should describe the dimensions. Actually since there suppliers PET preform changed its dimensions over the last months, I just left the different sizes there...

I will add dimensions so one could find a fitting sled.

**Comment by dr3x** [comment]
I tried the hot water trick, put water in a ceramic dish, floated the sled on the water and put it in the microwave on the beverage setting and it worked well to soften up the material so it could fit the tube, however the sled legs splayed out a little (warped) so flipped it over and pressed it back into shape and that seems to have fixed that issue. I'll find out when I get the circuit board but shouldn't be too difficult to reform it.

**Comment by dsvensson** [comment]
@universam1 any idea what design matches this one:

http://www.ebay.com/itm/132118452191

**Comment by universam1** [comment]
I've added the length of the different designs. So one might check which of these do fit to his preform. Still you can squeeze that PLA quite easily with hot air or water if necessary.

**Comment by dsvensson** [comment]
Is that outer or inner dimensions?

If I measure my container I get:

* Inner:
  * Width: 33.3mm
  * Height: 129.6mm
* Outer:
  * Width-Top-By-Opening: 36mm
  * Width-Middle-Of-Height: 39.2mm
  * Height: 133mm

So I'm not sure which one to pick here:

* drawer-36x133-thing2231986.stl
* drawer-38x133.stl

Maybe a README.md with where to measure would be a nice addition. I don't have a 3D-printer myself so I hope to avoid an extra print-request from my 3D-printing-contact.

**Comment by universam1** [comment]
It is the outer dia of the sled hence the inner of the container.

Your container is quite a bit thinner, I guess you have to hack it a lot, it might be really super tight if possible at all.

**Comment by gh112** [comment]
I need some help to choose a drawing. (first time 3d printing)

The PET I am going to order is 40.5x149 mm (inner diameter)
I am guessing that i need drawer-38x150-Geocaching.stl and maybe use some sandpaper, or possibly drawer-38x145-Geocaching.stl

Please advise if another one is more suitable

**Comment by einaruk** [comment]
Hi @dsvensson 
Were you able to fit a drawer to your 33x130 tube and made it work? I am having difficulties with a quite smaller tube.
