### ISSUE TITLE
Cannot install Drivers

### ISSUE THREAD

**Issue by StuChant** [universam1/iSpindel#478]
I'm having some issues which I'm hoping you can help with. I can't update the drivers or flash the wemos. when i plug it in, in device manager it does not show up in com Ports it shows up in other devices under the name FT232R USB UART
I've downloaded all necessary files and programs but can't seem to get anywhere.
Thanks in advance

**Comment by thegreatgunbantoad** [comment]
Try brewflasher.
https://github.com/thorrak/brewflasher/releases/tag/v1.0.1
It will only install the latest GitHub realese though, not your code.
