### ISSUE TITLE
Compiling error from git_rev.py

### ISSUE THREAD

**Issue by FernandoGarcia** [universam1/iSpindel#500]
## I'm submitting a ...
  - [x ] bug report

## Did you follow the general troubleshooting steps first:

- [ x] Searched for [similar reports already](https://github.com/universam1/iSpindel/issues) ?

## Report
Hi!

The script `git_rev.py` will cause compiling error when the code is downloaded as `.zip` instead `git clone`.

The compiling error:

```
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "git_rev.py", line 4, in <module>
    version = subprocess.check_output(tagcmd, shell=True).decode().strip()
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
```

The script searchs for `git flags` but files from `.zip` are not a `git` repository.

Please check [this ](https://community.platformio.org/t/pio-looking-for-py-in-a-cpp-project/21197)thread for more details.

Best regards.

**Comment by pppedrillo** [comment]
Related to https://github.com/universam1/iSpindel/pull/486 @MarcoCLA
