### ISSUE TITLE
https or redirections

### ISSUE THREAD

**Issue by joellord** [universam1/iSpindel#519]
Hi everyone,
   not sure if I just can't find the feature or if it's not existing. I want to make requests to a serverless endpoint that I have opened for POST requests. Right now, it seems like the requests from my iSpindel are sent via HTTP. I get a code 301 as a response which I believe is because it tries to redirect to the https page. 
   I am not very proficient with C, but looking at the code seems to indicate that it would be possible to send requests via https, I just can't seem to figure out how to configure my device to do so.

  Is there any way to send an HTTPS request? If not, this is a feature request :)

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please note that this repositories issues are intended for feature requests and bug reports.

## Did you follow the general troubleshooting steps first:

- [x] Follow through the [FAQ](https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md) ?
- [x] Checked the logs for errors in the terminal console ?
- [x] Searched for [similar reports already](https://github.com/universam1/iSpindel/issues) ?

**Comment by pppedrillo** [comment]
bool SenderClass::sendHTTPSPost(String server, String uri)

**Comment by joellord** [comment]
I saw that method, I just can't figure out how to configure the iSpindel to it ¯\_(ツ)_/¯

**Comment by joellord** [comment]
I just realized that I did not upgrade to the lastest firmware. I can now see the HTTPSPost option in the configuration menu.

¯\_(ツ)_/¯
