### ISSUE TITLE
Blynk 2.0 Changed the way to connect

### ISSUE THREAD

**Issue by sergioguimaraes** [universam1/iSpindel#548]
Blynk app changed the connection procedure and eliminated the token, but now it requires completely new features to be integrated with iSpindel.
Blynk 1.0 still works.

## I'm submitting a ...
  - [ ] bug report
  - [X ] feature request
  - [ ] support request => Please use the [Discussion](https://github.com/universam1/iSpindel/discussions) board instead!

**Comment by sikkepitje** [comment]
Blynk does not work anymore. The old smartphone app (now called "Blynk 0.1 (legacy)") can't run. The QR code to clone a project does not work in the new Blynk (app or website alike). The Blynk service type parameters are changed so the iSpindel can't be configured for working with the modern Blynk. Setting up Blynk is way different now. That's too bad
