### ISSUE TITLE
InfluxDB Authentication - Token

### ISSUE THREAD

**Issue by gwrichard** [universam1/iSpindel#552]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please use the [Discussion](https://github.com/universam1/iSpindel/discussions) board instead!

## Did you follow the general troubleshooting steps first:

- [x] Follow through the [FAQ](https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md) ?
- [x] Checked the logs for errors in the terminal console ?
- [x] Searched for [similar reports already](https://github.com/universam1/iSpindel/issues) ?

## Report

Am trying to connect the ispindel to InfluxDB 2.0.9. I keep getting a 401 unauthorized error.

InfluxDB 2.0 appears to have changed authentication methods to support tokens rather than username and passwords.

The configuration page for the ispindel does not support tokens when selecting the InfluxDB as the backend service to connect to.

[https://docs.influxdata.com/influxdb/v2.0/api/](url)

### Console Logs

Worker run!
mounting FS... mounted!
reading config file
parsed config:
{"Name":"ispindel","Token":"","Sleep":20,"Server":"192.168.10.100","API":8,"Port":8086,"Channel":0,"URI":"","DB":"ispindel","Username":"","Password":"","Job":"ispindel","Instance":"000","Hassio":false,"Vfact":191.8,"TS":0,"OWpin":12,"POLY":"-0.00031*tilt^2+0.557*tilt-14.054","SSID":"Richardson","PSK":"Australia12","Offset":[0,0,0,0,0,0]}
offsets not available
Boot-Mode: Deep-Sleep Wake

woken from deepsleep, normal mode
Samples:42 min:92.07 max:92.22 time:759
x: 1430 y: 15254 z: -564
Tilt: 92.13
Tacc: 23.65
Volt: 4.57
Temp: 23.56
Gravity: 34.63
IP: 192.168.10.122

calling InfluxDB
Sending to db: ispindel w/ credentials: :
INFLUXDB: posting to db: /write?db=ispindel
POST data: measurements,source=ispindel
tilt=92.13167,temperature=23.5625,temp_units="C",battery=4.567257,gravity=34.63198,interval=20,RSSI=-70
code: 401

Final-sleep: 20s; RT: 1228

## Steps to Reproduce (for bugs)

1. Setup configuration to connect to InfluxDB
2.
3.

## Context

I am trying to connect to InfluxDB 2.0.9

## Your Environment

- Firmware Version used: 7.1.2
- Browser Name and version: Chrome
- Service backend you have configured the iSpindel to talk to: InfluxDB 2.0.9

**Comment by cmoulliard** [comment]
If some of you are interested, I created a project able to route messages from MQTT to influxdb (or others recipients) where you could of course use your influxdb token : https://github.com/daboubeer/node-red

**Question**: Is the ispindel community interested to host here my integration/routing project ?

**Comment by cmoulliard** [comment]
No comments concerning my proposition ?

**Comment by PharmaJap** [comment]
As a workaround, have you tried setting up a v1 username/password with `influx v1 auth create`?
