### ISSUE TITLE
Doc link do not exist: https://www.ispindel.de/docs/tools/TestServer/Readme.md

### ISSUE THREAD

**Issue by cmoulliard** [universam1/iSpindel#557]
## Doc error 

The following link - https://www.ispindel.de/docs/tools/TestServer/Readme.md mentioned within the doc page - https://www.ispindel.de/docs/README_en.html#test-server under the section `Test server` --> simple server returns a `Error 404`

**Comment by thegreatgunbantoad** [comment]
The correct link would now seem to be: https://github.com/universam1/iSpindel/blob/master/tools/TestServer/Readme.md
It looks to be an issue in the English version but not the German.

**Comment by thegreatgunbantoad** [comment]
I think that: https://raw.githubusercontent.com/universam1/iSpindel/master/docs/README_en.md
needs to read: [simple test server](../tools/TestServer/Readme.md) on line124

**Comment by thegreatgunbantoad** [comment]
Pull request created: https://github.com/universam1/iSpindel/pull/561

**Comment by cmoulliard** [comment]
Link is working now

![Screenshot 2021-12-22 at 17 28 54](https://user-images.githubusercontent.com/463790/147124456-a0b2dca3-0870-4315-b937-660d71541ca9.png)
