### ISSUE TITLE
Wemos V4

### ISSUE THREAD

**Issue by porschepete** [universam1/iSpindel#560]
Getting everything together for my first build and I just realized I ordered the V4 Wemos D1 mini (does not appear they offer the official V3 anymore from Wemos). Looking at schematics it should work but I see a 470 resistor already on the board at the RST to D0 (IO16) deep sleep connection. Do I need to omit the BAT43 from the PCB and just bridge connection, keep it with the resistor, or remove resistor from D1 and bridge? Looking at the documentation it states either a BAT43 or 470ohm resistor. Thank you in advance for any help. 
V4:
![image](https://user-images.githubusercontent.com/96392384/146694364-3557ca01-e9b4-46c7-a44b-4875f0acbc1a.png)
V3:
![image](https://user-images.githubusercontent.com/96392384/146694391-8fcc03b1-9791-4b82-b165-f8d84288ed58.png)
Ispindel Diagram:
![image](https://user-images.githubusercontent.com/96392384/146694559-a55280a3-ed55-4093-9eda-202d4d11283a.png)

**Comment by thegreatgunbantoad** [comment]
I wouldn't be surprised if it works fine with the BAT43 as per the V3.  Give it a bash I guess and see how is goes.

**Comment by ErikdBr** [comment]
I guess V3.1 is EOL. https://www.wemos.cc/en/latest/d1/d1_mini.html

**Comment by porschepete** [comment]
@thegreatgunbantoad Sounds good, I’ll go ahead with the build and include the diode. Should hopefully have everything here after the holidays, will update this with my findings so anyone forward doesn’t run into issues.  

@ErikdBr Yep that’s what I assume, their Aliexpress store does not even have them for sale. Just knockoffs is all I can see available.

**Comment by ErikdBr** [comment]
> @ErikdBr Yep that’s what I assume, their Aliexpress store does not even have them for sale. Just knockoffs is all I can see available.
Please don't buy the knockoffs they're usually sheit.

**Comment by porschepete** [comment]
@ErikdBr Yep that’s what I’ve read, I have the official V4s D1 minis on the way. Just wanted to make sure that new resistor they put in doesn’t cause any issues.

**Comment by thegreatgunbantoad** [comment]
> > @ErikdBr Yep that’s what I assume, their Aliexpress >store does not even have them for sale. Just >knockoffs is all I can see available.
> 
> Please don't buy the knockoffs they're usually sheit.

For a long time that's all you could get.  They tend to either work or not, they don't tend to fail down the line.  But still get the legit stuff if you can, the fakers shouldn't be given money.  When I first started you just couldn't source the real stuff, glad they now have a store now.

**Comment by sym0nd0** [comment]
I've just ordered some of the V4 (as all the V3 Pros I ordered have been shite).

**Comment by pppedrillo** [comment]
@porschepete With the 470 resistor you could not get a reliable waking up from  the deep sleep. Here are alot of discussion about this issue , you can search for issues like "iSpindel sends its data only once", "iSpindel not always sends data" etc

**Comment by PharmaJap** [comment]
I don't see a need to remove the resistor, as long as the jumper remains open? Just bridge with a BAT43 at the through-hole, unless I'm missing something?

An interesting quirk of the v4 is the lack of an input diode to remove. If anyone has a sacrificial v4 they can remove the USB-C socket from, it'd be interesting to see the traces underneath to figure out a workaround.

**Comment by porschepete** [comment]
Finally got everything in the mail and all soldered up. Happy to report that everything seems to be working correctly so far, flashed without issue (using Linux) and deep sleep seems to be working correctly. Only time will tell with next batch to be sure but I am going to close this issue for now. 

> An interesting quirk of the v4 is the lack of an input diode to remove. If anyone has a sacrificial v4 they can remove the USB-C socket from, it'd be interesting to see the traces underneath to figure out a workaround.

@PharmaJap Correct, there does not appear to be any input diode present looking and the board and schematics of the V4. I did not want to sacrifice a board quite yet, just make sure not to plug into the Wemos with a battery installed.
