### ISSUE TITLE
Discussion: What about using a ispindel github org  (e.g.: https://github.com/ispindel, ...) ?

### ISSUE THREAD

**Issue by cmoulliard** [universam1/iSpindel#564]
## Discussion

What about using the a `ispindel` github org (e.g. https://github.com/ispindel) to host all the ispindel projects such as
- This one - https://github.com/universam1/iSpindel/i
- Site and documentation (jekyll, ...) - https://www.ispindel.de/
- Test server or clients (csharp, ...)
- Integration and routing (IoT collected data, MQTT, influxdb, grafana, ...) 
?

WDYT ? @universam1 @thegreatgunbantoad

**Comment by sikkepitje** [comment]
I think this is a great idea

**Comment by pppedrillo** [comment]
It is not an issue with a firmware and thus should go  into "Discussions", no?  
Same as another one, created by you  https://github.com/universam1/iSpindel/issues/562

**Comment by cmoulliard** [comment]
Do you want that I close this issue and create a https://github.com/universam1/iSpindel/discussions ? @pppedrillo

**Comment by cmoulliard** [comment]
Do you want that we create a https://github.com/universam1/iSpindel/discussions ? @pppedrillo @universam1
