### ISSUE TITLE
Firmware 7.2.0 identifies itself as 7.1.4

### ISSUE THREAD

**Issue by sikkepitje** [universam1/iSpindel#584]
Firmware 7.2.0 identifies itself as 7.1.4

![menu info klein](https://user-images.githubusercontent.com/14176764/175122388-8ff5be8d-9b0e-4aaa-a5ae-3f1834502b1e.png)

Great work BTW! 🍻

**Comment by thegreatgunbantoad** [comment]
Globals.h line 23 just needs fixing, likely to go up to 7.2.1.  Too easy to miss, not the first nor last time.
