### ISSUE TITLE
Same issue as Issue #571 - Issue with Ubidots API

### ISSUE THREAD

**Issue by chris160562** [universam1/iSpindel#599]
encountered exactly the same problem as in Issue 571 - connects to my WiFi, but does not want to send the info to Ubidots - made sure I am using the default Token. 

Used the Arduino IDE to receive the results from the serial monitor, and it got an IP within my IP range (using DHCP), connected to the WiFi (I could ping it with results when connected), but it gives the error "Sender: couldnt connect"

Seems to be a problem resolving the DNS of "industrial.api.ubidots.com". I substituted the ip-address of "industrial.api.ubidots.com" into the UBISERVER variable, recompiled it and it worked. This is just a temp work around, and not permanent fix.

An idea why the DNS would not be resolved?

Using firmware 7.2.1 in windows 11 environment.

**Comment by pppedrillo** [comment]
> An idea why the DNS would not be resolved?

DNS settings set in your WiFi router configuration, you need to check em. 
Nothing to do with iSpindel on this.
