### ISSUE TITLE
3600000000sec Sleep is too long

### ISSUE THREAD

**Issue by clrwl04** [universam1/iSpindel#60]
Running Firmware 3.4.4 on a bare (not connected) Wemos D1 Mini powered by my PC to test before final assembly.
The firmware loads and runs, I can see the first data pushed to Ubidots OK, but then nothing ever again.
Checking the serial output via  Arduino 1.8.2 desktop app is see the following, the sleep at the end catches my eye. If thats correct it sleeping for 41,666 days

After waiting 3.60 s, result 3
192.168.16.9
UBIDOTS: posting
POST /api/v1.6/devices/iSpindel000?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1
Host: things.ubidots.com
User-Agent: iSpindel000
Connection: close
Content-Type: application/json
Content-Length: 50

{"tilt":0.00,"temperature":-127.00,"battery":0.04}
WARNING: low Battery

**sleeping: 3600000000sec**

**Comment by universam1** [comment]
The firmware won't run on a not assembled device. That's mentioned in several other issues.
