### ISSUE TITLE
HTTP404 when clicking "Delete WiFi configuration and reboot" /r

### ISSUE THREAD

**Issue by GElkayam** [universam1/iSpindel#600]
https://github.com/universam1/iSpindel/blob/22951183beb5d70dbaa782aa87378bdc9019f0e7/pio/lib/WiFiManagerKT/WiFiManagerKT.cpp#L945

**Comment by universam1** [comment]
Please describe the issue first

**Comment by ErikdBr** [comment]
The issue is that when you click the /r link from the maintenance page you get this error:
![Screenshot_20230114-171711_Chrome](https://user-images.githubusercontent.com/48140503/212482986-8a634842-8ff2-4433-9306-f4349008d1b2.jpg)

**Comment by GElkayam** [comment]
Hi @universam1 , 
@ErikdBr is right, when clicking the /r link, you get a 404.
seems that in this commit, /r was changed to /reset (calling handleReset), so just need to align.
https://github.com/universam1/iSpindel/commit/e46bed1c341345bd8f53f69c8ae9d4da7b683a98#diff-e99471864a9b9c55df31c591e65a440ea3e22f1869c13667f1eb8254ca492d72L148

small cosmetic issue.

**Comment by ErikdBr** [comment]
> https://github.com/universam1/iSpindel/blob/22951183beb5d70dbaa782aa87378bdc9019f0e7/pio/lib/WiFiManagerKT/WiFiManagerKT.cpp#L945
And shouldn't this line be: `page += F("<tr><td><a href='/reset'>/r</a></td>");`

**Comment by GElkayam** [comment]
Hey @universam1 , I see Stalebot closed this issue? care to reopen?

**Comment by universam1** [comment]
fix released in 7.2.2
