### ISSUE TITLE
Wrong tilt value

### ISSUE THREAD

**Issue by Basbosbaas** [universam1/iSpindel#602]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please use the [Discussion](https://github.com/universam1/iSpindel/discussions) board instead!

## Did you follow the general troubleshooting steps first:

- [x] Follow through the [FAQ](https://github.com/universam1/iSpindel/blob/master/docs/FAQ-en.md) ?
- [x] Checked the logs for errors in the terminal console ?
- [x] Searched for [similar reports already](https://github.com/universam1/iSpindel/issues) ?

## Report

When I've callibrated the Ispindel on a flat surface its about 90 degrees tilt. But when I take it vertical it haves a tilt of about 45 degrees.

when 90 degrees (horizontal):
![image](https://user-images.githubusercontent.com/97124889/211904530-e67eaedb-fd1d-487c-93a5-113b9f6c7506.png)

when about 45 degrees:
![image](https://user-images.githubusercontent.com/97124889/211904739-a920350a-ac08-4f5a-8efd-5c1307043f07.png)

When about 0 degrees (vertical):
![image](https://user-images.githubusercontent.com/97124889/211904891-0b055f20-c72e-444b-81b6-95989aec64dd.png)

## Your Environment

- Firmware Version used: 7.2.1
- Browser Name and version: android

**Comment by thegreatgunbantoad** [comment]
You may well have a duff sensor.  There are a lot of poor quality counterfeit items out there (Especially the Wemos boards).  I have had my fair share of rubbish tilt sensors.  I assume you have checked that it's the right way around and all that kind of thing.  A picture of it laid down during calibration might help us out.  This is unlikely to be a software bug.

**Comment by ErikdBr** [comment]
Today I build a new iSpindel based on TheJeffrey 2.69 PCB and an original Wemos (Lolin) V3.1.0. I flashed it with the latest stable firmware: 7.2.1, did the calibration on a flat surface and these are my numbers, flat close to 90 degrees, vertical close (enough) to zero degrees in either direction (with the battery up or down), don't mind the gravity cause I didn't yet did the calibration in water so the default polynominal is still in there.
![Screenshot_20230114-164509_Chrome-COLLAGE](https://user-images.githubusercontent.com/48140503/212481597-4c035c0f-1c44-4c67-b4fc-1fe260b169ec.jpg)
![20230114_164359](https://user-images.githubusercontent.com/48140503/212481605-27fbbbb7-a1a0-4b3a-8b4b-c639c13684d0.jpg)

**Comment by Basbosbaas** [comment]
Ok, I get it. 

Unfortunately it is a bad gyroscope. I will buy some more and test it with new ones.

Thanks for all the quick responses.

**Comment by Basbosbaas** [comment]
Just for you info: I've bought new gyroscopes and everything works fine!
