### ISSUE TITLE
Add infill parameters for printing drawer

### ISSUE THREAD

**Issue by christoferjh** [universam1/iSpindel#63]
Unsure what infill I should use, or if should be solid?

**Comment by lekrom** [comment]
Should not matter much as it caries very little load. Mine came out great @ 15% (PLA) but you can probably go lower as long as you do not force it to hard into the preform and you are not too agressive when tightening cable ties and such.

**Comment by universam1** [comment]
This is indeed not critical, I have good results with ABS, PLA, with 1mm perimeter and 15% infill, but no need to force any of these.

**Comment by hocomadvies** [comment]
Sorry for asking but since I can not print 3d myself I have to look on https://www.3dhubs.com/ which file should I use to get the right one printed for the petling xl ? Or are all these files the same?

**Comment by universam1** [comment]
depends on the size of your petling, the sizes are described.
