### ISSUE TITLE
PCB file

### ISSUE THREAD

**Issue by Philusha1983** [universam1/iSpindel#66]
I saw in the documents that somebody made a PCB specially for this project, is it possible to share the file and the method you made it?

**Comment by universam1** [comment]
The pcb was made in a program that was not free for publication. 
So we would need to recreate it with KiCad or similar without these restrictions.

**Comment by Philusha1983** [comment]
Is Fritzing Program good enough?

**Comment by klovelace** [comment]
Here's a link to one board at a fab shop [https://pcbs.io/share/8gbKR].  Most people discuss replacing one of the resistors with a BAT43 diode

**Comment by universam1** [comment]
@klovelace check #59
