### ISSUE TITLE
New wifi network can not be saved

### ISSUE THREAD

**Issue by Philusha1983** [universam1/iSpindel#67]
I build one unit with my friend and then when I arrived at my house I tried to configure my home wifi network,  each time I try to save it's refusing to save. it.
any suggestions?

**Comment by universam1** [comment]
Does your password have special characters, spaces?

Please post the console output over USB/serial here so we can see what goes on.

**Comment by Philusha1983** [comment]
Ok I changed the password it had an !
Problem solved

Thanks
