### ISSUE TITLE
Gravity points after dot

### ISSUE THREAD

**Issue by Philusha1983** [universam1/iSpindel#68]
Is it possible to get more than 2 digits after dot?
There is a big difference between 1.06 and 1.07 in gravity calculation.

**Comment by universam1** [comment]
Good point, I do some major rework, could you please try this version?

[firmware.zip](https://github.com/universam1/iSpindel/files/1093955/firmware.zip)

**Comment by Philusha1983** [comment]
I'll test it later today. 
By the way what platform do you create the BIN file? 
My brewing partner is a developer, So he asked for this info, maybe he can help with this project.

**Comment by universam1** [comment]
I'm using platform.io

**Comment by tomcohen** [comment]
@universam1 
hi.  i just add the platform.io plugin into vscode IDE. init the project (wemos board and arduino libraries). how do i proceed  from here to export this project to binary file? 
thanks.

**Comment by universam1** [comment]
no answer, so closing
