### ISSUE TITLE
Protected battery?

### ISSUE THREAD

**Issue by bralexc** [universam1/iSpindel#72]
From the pictures it seems the suggested battery does not come with a protection circuit.
Aside from having to change the drawer, is it ok to use a battery with protection circuit?

**Comment by universam1** [comment]
The protection circuit is delivered by the charging board mentioned, which does not only take care of correct charging but also for over and undervoltage shutdown. Therefore it is obsolete to have a protected battery. However, if you want to anyway there are no objections.
