### ISSUE TITLE
question for FG instead of Plato

### ISSUE THREAD

**Issue by panzo19** [universam1/iSpindel#77]
Is there any plan to create FG.php instead of Plato.php or is there any optio to transform Plato to FG  in php file?

**Comment by universam1** [comment]
what php file are you referring to?

**Comment by panzo19** [comment]
in forlder tools/generic-TCP/web

**Comment by universam1** [comment]
Oh ok that's contribution from @Tozzi, you may open an issue on his repo.

**Comment by pumalyf** [comment]
I'm interested in turning into FG also, can you share any news?

**Comment by universam1** [comment]
@pumalyf @panzo19 you want to open an issue at @DottoreTozzi repository!

**Comment by DottoreTozzi** [comment]
I will look into it after my vacation.

**Comment by universam1** [comment]
@DottoreTozzi since your contribution is becoming a project, would it make sense to split it out into a dedicated project?

**Comment by jvels** [comment]
A input for @DottoreTozzi I have been playing with the chart lib. And have tried to make a "linked chart". It is "fake" data I have used. It might do plato/FG chart easier to read. Just an input.
![chart](https://user-images.githubusercontent.com/4173792/29484370-5a01b5e6-84bd-11e7-94d8-43a3b8e55db4.png)

**Comment by universam1** [comment]
I linked the repo of dottoreTozzi in the Readme, feel free to continue development there.
