### ISSUE TITLE
monitor.beer now support iSpindel 

### ISSUE THREAD

**Issue by 3sverd** [universam1/iSpindel#79]
Not an issue, just to say that https://monitor.beer now support iSpindel 100%, you can now have full control during fermentation. No longer need for creating your own graphs etc. Just register, get three months free and if you like it pay a small monthly amount to continue using https://monitor.beer. 

Continuous alcohol%.
Continuous yeast attenuation%.
Continuous fermentation%.
Continuous temperature.
Ongoing SG.
How long SG is stable in days.
Minimum temperature through fermentation.
Average temperature through fermentation.
Maximum temperature through fermentation.
Number of days fermentation.

**Comment by kabelbrand** [comment]
Naa, 3 month free, then it costs! Must write: Just register, pay and enjoy. Poor advertising...

**Comment by universam1** [comment]
assume it is fine, so closing for now
