### ISSUE TITLE
New calibration tool not working in FF and chrome

### ISSUE THREAD

**Issue by tommueller** [universam1/iSpindel#81]
The new [calibration tool](https://universam1.github.io/iSpindel/tools/calibration/calibration.htm) doesn't work for me in both FF 55 and latest chrome. There seems to be a cross-domain code loading problem. When I open the page I get: 
> Laden von gemischten aktiven Inhalten "http://code.jquery.com/jquery.min.js" wurde blockiert.

Adding a second dataset I get (logically concerning the error above):
> ReferenceError: $ is not defined

Cheers

**Comment by vstoms** [comment]
My workaround was to edit line 4 http to https.
