### ISSUE TITLE
Saving configuration make D2 crash and reboot

### ISSUE THREAD

**Issue by BouletNC** [universam1/iSpindel#84]
Hello,

I have a problem with my new Wemos D1 mini.

When I save configuration, the wemos crashed and reboot.

Here is my sefrial monitor log : 
FW 5.2.1
2.0.0(656edbf)
Worker run!
Boot-Mode: 5

Double Reset detected
mounting FS... mounted!

ERROR config corrupted
...........
ERROR no Wifi credentials

going to Config Mode
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
*WM: Scan done
*WM: Adding parameter
*WM: name
*WM: Adding parameter
*WM: sleep
*WM: Adding parameter
*WM: vfact
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: selAPI
*WM: Adding parameter
*WM: token
*WM: Adding parameter
*WM: server
*WM: Adding parameter
*WM: port
*WM: Adding parameter
*WM: url
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: POLYN
started Portal
*WM: SET AP
*WM: 
*WM: Configuring access point... 
*WM: iSpindel
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
*WM: Handle root
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
*WM: linksys
*WM: -69
*WM: MLS16722
*WM: -93
*WM: Sent config page
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED
*WM: WiFi save
*WM: Parameter
*WM: name
*WM: iSpindel000
*WM: Parameter
*WM: sleep
*WM: 900
*WM: Parameter
*WM: vfact
*WM: 191.80
*WM: Parameter
*WM: 
*WM: 
*WM: Parameter
*WM: 
*WM: 
*WM: Parameter
*WM: selAPI
*WM: 0
*WM: Parameter
*WM: token
*WM: 1234
*WM: Parameter
*WM: server
*WM: 
*WM: Parameter
*WM: port
*WM: 80
*WM: Parameter
*WM: url
*WM: 
*WM: Parameter
*WM: 
*WM: 
*WM: Parameter
*WM: POLYN
*WM: -0.00031*tilt^2+0.557*tilt-14.054
*WM: Sent wifi save page
I2C ERROR: 0 con:0
ERROR: OW DISCONNECTED

Exception (9):
epc1=0x401048c5 epc2=0x00000000 epc3=0x00000000 excvaddr=0xffffffff depc=0x00000000

ctx: sys 
sp: 3ffffdb0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff50:  00000056 00000001 4010407e 3ffef1b0  
3fffff60:  402397e9 3ffeff78 00000001 00000000  
3fffff70:  4022e8db 00000004 00000000 00000000  
3fffff80:  3fff30ac 4022e2ce 3fffdab0 00000000  
3fffff90:  3fffdcc0 3ffeb0a8 00000000 402388a3  
3fffffa0:  3ffeb0a8 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v00000000
~ld

FW 5.2.1
2.0.0(656edbf)
Worker run!
Boot-Mode: 2
mounting FS... mounted!

ERROR config corrupted
...........
ERROR no Wifi credentials

going to Config Mode

Thank you for your help.

Benoit

**Comment by universam1** [comment]
The device crashes because you have not connected the GY nor the DS sensors. This is not supported.
