### ISSUE TITLE
Minimizing the 3d drawer for smaller PET

### ISSUE THREAD

**Issue by Philusha1983** [universam1/iSpindel#88]
I want to create a smaller version of the drawer.
Are there technical issues that I need to take into consideration? 
![image](https://user-images.githubusercontent.com/7344475/29931103-ed27f4c4-8e78-11e7-92e3-2d5bc423737c.png)

**Comment by bralexc** [comment]
You shouldn't have any issues other then the reduced turned on time due to
smaller battery capacity.

In fact, someone I know made one out of a Falcon tube using a 14500 battery
(2200 mAh).

Em 31 de ago de 2017 12:20 PM, "Philip Levin Slesarev" <
notifications@github.com> escreveu:

**Comment by deedos** [comment]
"In fact, someone I know made one out of a Falcon tube using a 14500 battery
(2200 mAh)." 
That' s cool. Does he have a project for the drawer ? Is it ok just replace de battery?

**Comment by bralexc** [comment]
No project, sorry. He had to remove the TP4056 due to size restrictions, so to recharge he always needs to take the battery out.

**Comment by universam1** [comment]
assume it is fine, so closing for now
