### ISSUE TITLE
English circuit diagram is not in english

### ISSUE THREAD

**Issue by XREvo** [universam1/iSpindel#89]
The image at [circuit_diagram_en](https://github.com/universam1/iSpindel/blob/master/docs/https://github.com/universam1/iSpindel/blob/master/docs/circuit_diagram_en.md.md) is not in english (since the page is related to english content).
Can you translate it?

**Comment by Paiakan** [comment]
![ispindel_schematic_en](https://user-images.githubusercontent.com/32596482/31309731-80bfd9b8-ab61-11e7-8150-8cc394ed058e.png)
![ispindel_schematic_pt](https://user-images.githubusercontent.com/32596482/31309732-836483e4-ab61-11e7-878d-98deb145b47b.png)

Done. I also included the BAT43 diode as option to the 470 ohm resistor and also included a Portuguese version of the diagram.

By the way, I can help translating the "READ ME" file to portuguese, if you are interested.

**Comment by universam1** [comment]
Thank you @Paiakan this is highly appreciated! 👍 

I would love to include other languages as well and feel free to open a pull request for updates in this regard.

**Comment by Paiakan** [comment]
Weel, I am new in this kind of collaboration. Tried to translate creating a fork but I believe my first atempt didn't work.

**Comment by XREvo** [comment]
Thank you @Paiakan

**Comment by universam1** [comment]
merged your contributions, thank you!
