### ISSUE TITLE
bin file vertion 5.4.x?

### ISSUE THREAD

**Issue by jvels** [universam1/iSpindel#91]
Hi

I see in the change log there are a version 5.4.x, but there are not a bin file in the bin folder?

/Jesper

**Comment by jvels** [comment]
thx

**Comment by charliwest** [comment]
Do you have a link please? I just tried from the website and got this link to the zip file https://github.com/universam1/iSpindel/zipball/master but still no 5.4.x versions in the bin dir.

**Comment by universam1** [comment]
thanks @charliwest
