### ISSUE TITLE
It's asking for Token with HTTP

### ISSUE THREAD

**Issue by zandoga** [universam1/iSpindel#92]
![screenshot_20170904-223418](https://user-images.githubusercontent.com/29188252/30044584-ee8a1468-91cb-11e7-949e-02022ee56f6d.png)

**Comment by universam1** [comment]
What's the error?

**Comment by zandoga** [comment]
Doesn't communicate with BrewPiLess, it was communicating with 5.2.3.. If
it's ok to leave Token empty than nevermind, please close the issue. I'll
try again.

**Comment by universam1** [comment]
Exactly, if the token is left empty it is skipped. Please try and report.

**Comment by zandoga** [comment]
Tried again, no luck. Reversed back to 5.2.3 and it also doesn't work.
Ubidots works just fine. Looking at the serial monitor it seems that it
connects to BrewPiLess but the gravity doesn't get displayed. It's probably
an user or BrewPiLess issue.

On Sep 5, 2017 8:51 AM, "universam1" <notifications@github.com> wrote:

Exactly, if the token is left empty it is skipped. Please try and report.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/universam1/iSpindel/issues/92#issuecomment-327165569>,
or mute the thread

**Comment by ksga** [comment]
Had the same issue... Try to select another comm option, and then reselecting http - now the options should show correctly...
