### ISSUE TITLE
Issue connecting iSpindle to BrewPiLess

### ISSUE THREAD

**Issue by pronkster** [universam1/iSpindel#93]
I am having issues connecting iSpindle to brewpiless. Everything was working fine before I installed firmware version 5.2.1. Ubidots is working fine and I can see network connectivity is up. I can ping when it is out of sleep.. The monitor is showing no errors. I have re-installed a few times but still no luck.. Any idea what I can do next?

Thanks

**Comment by lekrom** [comment]
I have the same problem...

**Comment by universam1** [comment]
Please post the console output when a connection to BrewPiLess is established so we can discover what's going wrong.

**Comment by universam1** [comment]
Here is a bugfixed version, using a library now to perform the post. Please also monitor the execution time in this regard and let me know how it works.
[firmware.zip](https://github.com/universam1/iSpindel/files/1366844/firmware.zip)

**Comment by universam1** [comment]
closing in favor of #103
